ControlLogic::MotorChannel Class Reference
Public Member Functions
MotorChannel (int ch)
void SetMotion (filament_motion_enum m)
Set the motion mode for this channel.
float GetXByPressure (float pressure_voltage, float control_voltage, float time_E, pressure_control_enum control_type, float sign)
Calculate motor output based on Pressure Control logic.
void Run (float time_E)
Main Motor Loop for this channel.
void UpdateLEDStatus ()
Update the Lane LED based on status.
Public Attributes
int CHx
filament_motion_enum motion = filament_motion_enum::stop
uint64_t motor_stop_time = 0
MOTOR_PID PID_speed = MOTOR_PID(2, 20, 0)
MOTOR_PID PID_pressure = MOTOR_PID(1500, 0, 0)
float pwm_zero = 500
float dir = 0
float target_velocity = 0
float target_distance = 0
float accumulated_distance = 0
Detailed Description
Definition at line 324 of file ControlLogic.cpp.
Constructor & Destructor Documentation
MotorChannel()
ControlLogic::MotorChannel::MotorChannel (int ch) [inline]
Definition at line 337 of file ControlLogic.cpp.
: CHx(ch) {}
References CHx.
Member Function Documentation
GetXByPressure()
float ControlLogic::MotorChannel::GetXByPressure (float pressure_voltage, float control_voltage, float time_E, pressure_control_enum control_type, float sign) [inline]
Calculate motor output based on Pressure Control logic.
Parameters
pressure_voltage Current pressure ADC voltage.
control_voltage Target/Limit voltage.
time_E Time step.
control_type Mode: All (PID always), Less (Only if < limit), Over (Only if > limit).
sign Direction sign.
Returns
float Motor PWM contribution.
Definition at line 366 of file ControlLogic.cpp.
                                                                                                                                          {
            float x=0;
            switch (control_type) {
                case pressure_control_enum::all:
                    x = sign * PID_pressure.Calculate(MC_PULL_stu_raw[CHx] - control_voltage, time_E);
                    break;
                case pressure_control_enum::less_pressure:
                    if (pressure_voltage < control_voltage)
                        x = sign * PID_pressure.Calculate(MC_PULL_stu_raw[CHx] - control_voltage, time_E);
                    break;
                case pressure_control_enum::over_pressure:
                    if (pressure_voltage > control_voltage)
                        x = sign * PID_pressure.Calculate(MC_PULL_stu_raw[CHx] - control_voltage, time_E);
                    break;
            }
            if (x > 0) {
                x = x * x / 250;
            } else {
                x = -x * x / 250;
            }
            return x;
        }
References ControlLogic::all, CHx, ControlLogic::less_pressure, ControlLogic::MC_PULL_stu_raw, ControlLogic::over_pressure, and PID_pressure.
Referenced by Run().
Run()
void ControlLogic::MotorChannel::Run (float time_E) [inline]
Main Motor Loop for this channel.
Updates PWM output based on current motion state, PID logic, and pressure sensors. Handles velocity control, distance accumulation, and pressure maintenance.
Parameters
time_E Time elapsed in seconds.
Definition at line 398 of file ControlLogic.cpp.
                               {
            // Track distance for all movement types if needed, but critical for Klipper Move
            // speed_as5600 is in mm/s? AS5600_Update says: speedx = dist_E / time_E. dist_E is mm.
            // So speed_as5600 is mm/s.
            
            float dist_step = fabs(speed_as5600[CHx] * time_E);
            if (is_backing_out) {
                last_total_distance[CHx] += dist_step;
            }
            if (motion == filament_motion_enum::velocity_control && target_distance > 0) {
                 accumulated_distance += dist_step;
                 if (accumulated_distance >= target_distance) {
                      SetMotion(filament_motion_enum::stop);
                      // TODO: Send async completion event? Or just stop.
                      // Klipper polls or waits?
                      // The spec says MOVE returns when done? Or "TELEMETRY".
                      // If open-loop, success is assumed.
                      // But effectively we are closed-loop on distance now.
                 }
            }
            
            float speed_set = 0;
            float now_speed = speed_as5600[CHx];
            float x = 0;
            
            if (motion == filament_motion_enum::pressure_ctrl_idle) { // Idle
                bool pid_invert = false;
                switch(CHx) {
                    case 0: pid_invert = MOTOR_PID_INVERT_CH1; break;
                    case 1: pid_invert = MOTOR_PID_INVERT_CH2; break;
                    case 2: pid_invert = MOTOR_PID_INVERT_CH3; break;
                    case 3: pid_invert = MOTOR_PID_INVERT_CH4; break;
                }
                float pid_sign = dir * (pid_invert ? -1.0f : 1.0f);
                if (MC_ONLINE_key_stu[CHx] == 0) {
                    Assist_send_filament[CHx] = true;
                }
                if (Assist_send_filament[CHx] && is_two) {
                    if (MC_ONLINE_key_stu[CHx] == 2) x = -dir * 666;
                    else if (MC_ONLINE_key_stu[CHx] == 1) {
                         // Timer logic...
                    }
                } else {
                    if (MC_ONLINE_key_stu[CHx] != 0 && MC_PULL_stu[CHx] != 0) {
                        x = pid_sign * PID_pressure.Calculate(MC_PULL_stu_raw[CHx] - 1.65, time_E);
                    } else {
                        x = 0; PID_pressure.Clear();
                    }
                }
            } else if (MC_ONLINE_key_stu[CHx] != 0 || motion == filament_motion_enum::velocity_control) { // Allow vel control without sensor
                bool pid_invert = false;
                switch(CHx) {
                    case 0: pid_invert = MOTOR_PID_INVERT_CH1; break;
                    case 1: pid_invert = MOTOR_PID_INVERT_CH2; break;
                    case 2: pid_invert = MOTOR_PID_INVERT_CH3; break;
                    case 3: pid_invert = MOTOR_PID_INVERT_CH4; break;
                }
                float pid_sign = dir * (pid_invert ? -1.0f : 1.0f);
                 if (motion == filament_motion_enum::pressure_ctrl_in_use) {
                     if (pull_state_old) {
                         if (MC_PULL_stu_raw[CHx] < 1.55) pull_state_old = false;
                     } else {
                         if (MC_PULL_stu_raw[CHx] < 1.65) x = GetXByPressure(MC_PULL_stu_raw[CHx], 1.65, time_E, pressure_control_enum::less_pressure, pid_sign);
                         else if (MC_PULL_stu_raw[CHx] > 1.7) x = GetXByPressure(MC_PULL_stu_raw[CHx], 1.7, time_E, pressure_control_enum::over_pressure, pid_sign);
                     }
                 } else {
                     if (motion == filament_motion_enum::stop) {
                         PID_speed.Clear(); Hardware::PWM_Set(CHx, 0); return;
                     }
                     if (motion == filament_motion_enum::send) {
                         if (device_type_addr == BambuBus_AMS_lite) {
                             if (MC_PULL_stu_raw[CHx] < PULL_VOLTAGE_SEND_MAX) speed_set = MOTOR_SPEED_AMS_LITE_SEND; else speed_set = 0;
                         } else speed_set = MOTOR_SPEED_SEND;
                     }
                     if (motion == filament_motion_enum::slow_send) speed_set = MOTOR_SPEED_SLOW_SEND;
                     if (motion == filament_motion_enum::pull) speed_set = -MOTOR_SPEED_PULL;
                     if (motion == filament_motion_enum::velocity_control) speed_set = target_velocity; // Use Override
                     
                     x = dir * PID_speed.Calculate(now_speed - speed_set, time_E);
                 }
            } else {
                x = 0;
            }
            
            if (x > 10) x += pwm_zero;
            else if (x < -10) x -= pwm_zero;
            else x = 0;
            
            if (x > 1000) x = 1000;
            if (x < -1000) x = -1000;
            
            Hardware::PWM_Set(CHx, (int)x);
            UpdateLEDStatus();
        }
References accumulated_distance, ControlLogic::Assist_send_filament, BambuBus_AMS_lite, CHx, device_type_addr, dir, GetXByPressure(), ControlLogic::is_backing_out, ControlLogic::is_two, last_total_distance, ControlLogic::less_pressure, ControlLogic::MC_ONLINE_key_stu, ControlLogic::MC_PULL_stu, ControlLogic::MC_PULL_stu_raw, motion, MOTOR_PID_INVERT_CH1, MOTOR_PID_INVERT_CH2, MOTOR_PID_INVERT_CH3, MOTOR_PID_INVERT_CH4, MOTOR_SPEED_AMS_LITE_SEND, MOTOR_SPEED_PULL, MOTOR_SPEED_SEND, MOTOR_SPEED_SLOW_SEND, ControlLogic::over_pressure, PID_pressure, PID_speed, ControlLogic::pressure_ctrl_idle, ControlLogic::pressure_ctrl_in_use, ControlLogic::pull, ControlLogic::pull_state_old, PULL_VOLTAGE_SEND_MAX, Hardware::PWM_Set(), pwm_zero, ControlLogic::send, SetMotion(), ControlLogic::slow_send, ControlLogic::speed_as5600, ControlLogic::stop, target_distance, target_velocity, UpdateLEDStatus(), and ControlLogic::velocity_control.
SetMotion()
void ControlLogic::MotorChannel::SetMotion (filament_motion_enum m) [inline]
Set the motion mode for this channel.
Resets PID and counters if mode changes.
Parameters
m New Motion Enum.
Definition at line 347 of file ControlLogic.cpp.
                                               {
            if (motion != m) {
                motion = m;
                PID_speed.Clear();
                accumulated_distance = 0; // Reset on mode change
            }
        }
References accumulated_distance, motion, and PID_speed.
Referenced by Run().
UpdateLEDStatus()
void ControlLogic::MotorChannel::UpdateLEDStatus () [inline]
Update the Lane LED based on status.
Green/Red based on Pressure triggers, or User Color if idle+online.
Definition at line 501 of file ControlLogic.cpp.
                               {
            if (MC_PULL_stu[CHx] == 1) {
                Hardware::LED_SetColor(CHx, 0, 255, 0, 0);
            } else if (MC_PULL_stu[CHx] == -1) {
                Hardware::LED_SetColor(CHx, 0, 0, 0, 255);
            } else if (MC_PULL_stu[CHx] == 0) {
                 if (MC_ONLINE_key_stu[CHx] == 1) {
                     FilamentState &f = data_save.filament[CHx];
                     Hardware::LED_SetColor(CHx, 0, f.color_R, f.color_G, f.color_B);
                 } else {
                     Hardware::LED_SetColor(CHx, 0, 0, 0, 0);
                 }
            }
        }
References CHx, FilamentInfo::color_B, FilamentInfo::color_G, FilamentInfo::color_R, data_save, Hardware::LED_SetColor(), ControlLogic::MC_ONLINE_key_stu, and ControlLogic::MC_PULL_stu.
Referenced by Run().
Member Data Documentation
accumulated_distance
float ControlLogic::MotorChannel::accumulated_distance = 0
Definition at line 335 of file ControlLogic.cpp.
Referenced by Run(), and SetMotion().
CHx
int ControlLogic::MotorChannel::CHx
Definition at line 326 of file ControlLogic.cpp.
Referenced by GetXByPressure(), MotorChannel(), Run(), and UpdateLEDStatus().
dir
float ControlLogic::MotorChannel::dir = 0
Definition at line 332 of file ControlLogic.cpp.
Referenced by Run().
motion
filament_motion_enum ControlLogic::MotorChannel::motion = filament_motion_enum::stop
Definition at line 327 of file ControlLogic.cpp.
Referenced by Run(), and SetMotion().
motor_stop_time
uint64_t ControlLogic::MotorChannel::motor_stop_time = 0
Definition at line 328 of file ControlLogic.cpp.
PID_pressure
MOTOR_PID ControlLogic::MotorChannel::PID_pressure = MOTOR_PID(1500, 0, 0)
Definition at line 330 of file ControlLogic.cpp.
Referenced by GetXByPressure(), and Run().
PID_speed
MOTOR_PID ControlLogic::MotorChannel::PID_speed = MOTOR_PID(2, 20, 0)
Definition at line 329 of file ControlLogic.cpp.
Referenced by Run(), and SetMotion().
pwm_zero
float ControlLogic::MotorChannel::pwm_zero = 500
Definition at line 331 of file ControlLogic.cpp.
Referenced by Run().
target_distance
float ControlLogic::MotorChannel::target_distance = 0
Definition at line 334 of file ControlLogic.cpp.
Referenced by Run().
target_velocity
float ControlLogic::MotorChannel::target_velocity = 0
Definition at line 333 of file ControlLogic.cpp.
Referenced by Run().
The documentation for this class was generated from the following file:
src/ControlLogic.cpp