UnitState Class Reference
#include <UnitState.h>
Static Public Member Functions
static FilamentState & GetFilament (int index)
Get the configuration specific to a filament index.
static int GetCurrentFilamentIndex ()
Get the currently active filament index.
static void SetCurrentFilamentIndex (int index)
Set the currently active filament index.
static uint8_t GetFilamentUseFlag ()
Get the Filament Use Status Flag.
static void SetFilamentUseFlag (uint8_t flag)
Set the Filament Use Status Flag.
static void SetBusAddress (uint16_t addr)
Set the Bus Address used by this device (AMS vs AMS Lite).
static uint16_t GetBusAddress ()
Get the Bus Address.
static const char * GetModel ()
static const char * GetVersion ()
static const char * GetSerialNumber ()
Detailed Description
Definition at line 69 of file UnitState.h.
Member Function Documentation
GetBusAddress()
uint16_t UnitState::GetBusAddress () [static]
Get the Bus Address.
Returns
uint16_t The configured address.
Definition at line 118 of file ControlLogic.cpp.
                                  {
    return device_type_addr;
}
References device_type_addr.
GetCurrentFilamentIndex()
int UnitState::GetCurrentFilamentIndex () [static]
Get the currently active filament index.
Returns
int Index (0-3) or 0xFF if none/unknown.
Definition at line 72 of file ControlLogic.cpp.
                                       {
    return data_save.BambuBus_now_filament_num;
}
References data_save.
Referenced by KlipperCLI::HandleMove().
GetFilament()
FilamentState & UnitState::GetFilament (int index) [static]
Get the configuration specific to a filament index.
Parameters
index 0-3 for specific lane. Bounded to 0-3.
Returns
FilamentState& Reference to the state object.
Definition at line 62 of file ControlLogic.cpp.
                                               {
    if(index < 0 || index >= 4) return data_save.filament[0]; // Boundary safety
    return data_save.filament[index];
}
References data_save.
Referenced by KlipperCLI::HandleGetFilamentInfo(), KlipperCLI::HandleSetFilamentInfo(), and KlipperCLI::HandleStatus().
GetFilamentUseFlag()
uint8_t UnitState::GetFilamentUseFlag () [static]
Get the Filament Use Status Flag.
Returns
uint8_t Flags indicating usage state (e.g. 0x02 busy, 0x04 in use).
Definition at line 90 of file ControlLogic.cpp.
                                      {
    return data_save.filament_use_flag;
}
References data_save.
GetModel()
const char * UnitState::GetModel () [static]
Definition at line 123 of file ControlLogic.cpp.
{ return unit_model; }
References unit_model.
GetSerialNumber()
const char * UnitState::GetSerialNumber () [static]
Definition at line 127 of file ControlLogic.cpp.
{ return unit_serial; }
References unit_serial.
GetVersion()
const char * UnitState::GetVersion () [static]
Definition at line 125 of file ControlLogic.cpp.
{ return unit_version; }
References unit_version.
Referenced by KlipperCLI::HandlePing().
SetBusAddress()
void UnitState::SetBusAddress (uint16_t addr) [static]
Set the Bus Address used by this device (AMS vs AMS Lite).
Parameters
addr The address/type identifier.
Definition at line 109 of file ControlLogic.cpp.
                                           {
    device_type_addr = addr;
}
References device_type_addr.
SetCurrentFilamentIndex()
void UnitState::SetCurrentFilamentIndex (int index) [static]
Set the currently active filament index.
Parameters
index Index (0-3) or 0xFF.
Definition at line 81 of file ControlLogic.cpp.
                                                 {
    data_save.BambuBus_now_filament_num = index;
}
References data_save.
Referenced by KlipperCLI::HandleSelectLane().
SetFilamentUseFlag()
void UnitState::SetFilamentUseFlag (uint8_t flag) [static]
Set the Filament Use Status Flag.
Parameters
flag New flag status.
Definition at line 99 of file ControlLogic.cpp.
                                               {
    data_save.filament_use_flag = flag;
}
References data_save.
The documentation for this class was generated from the following files:
src/UnitState.h
src/ControlLogic.cpp