ControlLogic Namespace Reference
Classes
class MOTOR_PID
class MotorChannel
Enumerations
enum filament_now_position_enum {
filament_idle
, filament_sending_out
, filament_using
, filament_pulling_back
,
filament_redetect
, filament_loading
, filament_unloading
 }
enum class filament_motion_enum {
stop
, send
, pull
, slow_send
,
pressure_ctrl_idle
, pressure_ctrl_in_use
, pressure_ctrl_on_use
, velocity_control
 }
enum class pressure_control_enum { less_pressure
, all
, over_pressure
 }
enum class BootMode : uint32_t { BambuBus = 0
, Klipper = 1
 }
Functions
uint64_t get_time64 ()
void motor_motion_switch ()
State Machine for BambuBus Logic.
void MC_PULL_ONLINE_read ()
Read Analog Sensors and Update State.
void StartLoadFilament (int tray, int length_mm)
Initiate a Filament Load sequence for a specific tray.
void StartUnloadFilament (int tray, int length_mm)
Initiate a Filament Unload sequence for a specific tray.
void MoveAxis (int axis, float dist_mm, float speed)
Manually move an axis (Klipper Primitive).
void StopAll ()
Stop all motors.
void SetAutoFeed (int lane, bool enable)
Enable/Disable Auto-Feed (Pressure Control) for a lane.
uint16_t GetSensorState ()
Get a bitmask of sensor states.
int GetLaneMotion (int lane)
Get the current motion state of a lane.
void AS5600_Update (float time_E)
Update Odometer and Speed from AS5600 sensors.
void SaveSettings ()
Commit settings to Flash memory.
void SetNeedToSave ()
Flag that settings need to be saved.
bool Prepare_For_filament_Pull_Back (float_t OUT_filament_meters)
Check if pullback is required (Smart Pullback Logic).
void Run ()
Main Control Loop.
void LoadSettings ()
Load settings from Flash memory.
void Init ()
Initialize ControlLogic.
BootMode InitBootCheck ()
Check Boot Mode (Button Press at Startup).
BootMode GetBootMode ()
Get current Boot Mode.
void UpdateConnectivity (bool online)
Update connectivity status (Online/Offline).
void ProcessMotionShortLogic (uint8_t ams_num, uint8_t statu_flags, uint8_t read_num, uint8_t fliment_motion_flag)
Core logic for processing Short Motion packets.
void ProcessMotionShort (uint8_t *buffer, uint16_t length)
Handler for Filament Motion Short packet (0x03).
void ProcessMotionLong (uint8_t *buffer, uint16_t length)
Handler for Filament Motion Long packet (0x04).
void ProcessOnlineDetect (uint8_t *buffer, uint16_t length)
Handler for Online Detect (0x05).
void ProcessREQx6 (uint8_t *buffer, uint16_t length)
Handler for REQx6 (0x06).
void ProcessHeartbeat (uint8_t *buffer, uint16_t length)
Handler for Heartbeat (0x20).
void ProcessSetFilamentInfo (uint8_t *buffer, uint16_t length)
Handler for Set Filament Info (0x08 - Short).
void SetFilamentInfoAction (int id, const FilamentInfo &info, float meters)
Action helper to update filament metadata.
void ProcessLongPacket (struct long_packge_data &data)
Handler/Dispatcher for Long Packets.
uint16_t GetDeviceType ()
Get the configured device type.
void ProcessMotionLongLogic (uint8_t *payload, uint16_t length)
Variables
float PULL_voltage_up = 1.85f
float PULL_voltage_down = 1.45f
float_t P1X_OUT_filament_meters = 200.0f
static float speed_as5600 [4] = {0, 0, 0, 0}
static float MC_PULL_stu_raw [4] = {0, 0, 0, 0}
static int MC_PULL_stu [4] = {0, 0, 0, 0}
static float MC_ONLINE_key_stu_raw [4] = {0, 0, 0, 0}
static int MC_ONLINE_key_stu [4] = {0, 0, 0, 0}
static bool Assist_send_filament [4] = {false}
static bool pull_state_old = false
static bool is_backing_out = false
static const bool is_two = true
static int32_t as5600_distance_save [4] = {0, 0, 0, 0}
static int32_t unload_target_dist [4] = {0, 0, 0, 0}
static float unload_start_meters [4] = {0, 0, 0, 0}
static filament_now_position_enum filament_now_position [4] = {filament_idle, filament_idle, filament_idle, filament_idle}
static bool Bambubus_need_to_save = false
static uint64_t save_timer = 0
static MotorChannel motors [4] = {0, 1, 2, 3}
Enumeration Type Documentation
BootMode
enum class ControlLogic::BootMode : uint32_t [strong]
Enumerator
BambuBus
Klipper
Definition at line 14 of file ControlLogic.h.
                        : uint32_t {
        BambuBus = 0,
        Klipper = 1
    };
filament_motion_enum
enum class ControlLogic::filament_motion_enum [strong]
Enumerator
stop
send
pull
slow_send
pressure_ctrl_idle
pressure_ctrl_in_use
pressure_ctrl_on_use
velocity_control
Definition at line 181 of file ControlLogic.cpp.
    {
        stop,
        send,
        pull,
        slow_send,
        pressure_ctrl_idle,
        pressure_ctrl_in_use,
        pressure_ctrl_on_use,
        velocity_control // Added for Klipper
    };
filament_now_position_enum
enum ControlLogic::filament_now_position_enum
Enumerator
filament_idle
filament_sending_out
filament_using
filament_pulling_back
filament_redetect
filament_loading
filament_unloading
Definition at line 170 of file ControlLogic.cpp.
    {
        filament_idle,
        filament_sending_out,
        filament_using,
        filament_pulling_back,
        filament_redetect,
        filament_loading, // Added for LOAD_FILAMENT command
        filament_unloading, // Added for UNLOAD_FILAMENT command
    };
pressure_control_enum
enum class ControlLogic::pressure_control_enum [strong]
Enumerator
less_pressure
all
over_pressure
Definition at line 322 of file ControlLogic.cpp.
{ less_pressure, all, over_pressure };
Function Documentation
AS5600_Update()
void ControlLogic::AS5600_Update (float time_E)
Update Odometer and Speed from AS5600 sensors.
Reads angles, calculates delta, computes speed and distance. Updates global odometer meters for the filament.
Parameters
time_E Time elapsed.
Definition at line 694 of file ControlLogic.cpp.
                                     {
        MC_AS5600.updata_angle();
        for(int i=0; i<4; i++) {
            if (!MC_AS5600.online[i]) {
                speed_as5600[i] = 0; as5600_distance_save[i] = 0; continue;
            }
            int32_t now = MC_AS5600.raw_angle[i];
            int32_t last = as5600_distance_save[i];
            int cir_E = 0;
            if (now > 3072 && last <= 1024) cir_E = -4096;
            else if (now <= 1024 && last > 3072) cir_E = 4096;
            
            float dist_E = -(float)(now - last + cir_E) * AS5600_PI * 7.5 / 4096;
            as5600_distance_save[i] = now;
            
            float speedx = dist_E / (time_E > 0 ? time_E : 0.001f);
            speed_as5600[i] = speedx;
            
            data_save.filament[i].meters += dist_E / 1000.0f;
        }
    }
References as5600_distance_save, AS5600_PI, data_save, MC_AS5600, and speed_as5600.
Referenced by Run().
get_time64()
uint64_t ControlLogic::get_time64 () [inline]
Definition at line 227 of file ControlLogic.cpp.
{ return Hardware::GetTime(); }
References Hardware::GetTime().
Referenced by motor_motion_switch(), and ProcessMotionShortLogic().
GetBootMode()
BootMode ControlLogic::GetBootMode ()
Get current Boot Mode.
Returns
BootMode
Definition at line 936 of file ControlLogic.cpp.
                           {
        return (BootMode)data_save.boot_mode;
    }
References data_save.
Referenced by CommandRouter::Run().
GetDeviceType()
uint16_t ControlLogic::GetDeviceType ()
Get the configured device type.
Returns
uint16_t Device Type ID (AMS / AMS Lite).
Definition at line 1453 of file ControlLogic.cpp.
{ return device_type_addr; }
References device_type_addr.
GetLaneMotion()
int ControlLogic::GetLaneMotion (int lane)
Get the current motion state of a lane.
Parameters
lane Lane index.
Returns
int Motion Enum integer value.
Definition at line 679 of file ControlLogic.cpp.
                                {
        if(lane < 0 || lane >= 4) return 0;
        return (int)motors[lane].motion;
    }
References motors.
Referenced by KlipperCLI::HandleStatus().
GetSensorState()
uint16_t ControlLogic::GetSensorState ()
Get a bitmask of sensor states.
Returns
uint16_t Bitmask (Bit i = Filament Present Lane i).
Definition at line 662 of file ControlLogic.cpp.
                              {
         // [0:3] = Filament Present (MC_ONLINE_key_stu)
         // [4:7] = Buffer/Online?
         uint16_t state = 0;
         for(int i=0; i<4; i++) {
             if(MC_ONLINE_key_stu[i] != 0) state |= (1 << i);
         }
         return state;
    }
References MC_ONLINE_key_stu.
Referenced by KlipperCLI::HandleGetSensors(), and KlipperCLI::HandleStatus().
Init()
void ControlLogic::Init ()
Initialize ControlLogic.
Initializes Hardware (ADC, PWM), Loads Settings, and Initializes AS5600.
Definition at line 870 of file ControlLogic.cpp.
                {
        Hardware::ADC_Init();
        Hardware::PWM_Init();
        LoadSettings();
        MC_AS5600.init(AS5600_SCL, AS5600_SDA, 4);
        
        for(int i=0; i<4; i++) {
            int d = mc_save.Motion_control_dir[i];
            if (d == 0) d = 1;
            
            bool invert = false;
            switch(i) {
                case 0: invert = MOTOR_INVERT_CH1; break;
                case 1: invert = MOTOR_INVERT_CH2; break;
                case 2: invert = MOTOR_INVERT_CH3; break;
                case 3: invert = MOTOR_INVERT_CH4; break;
            }
            
            if (invert) d = -d;
            motors[i].dir = (float)d;
            
            last_total_distance[i] = data_save.filament[i].meters;
        }
    }
References Hardware::ADC_Init(), AS5600_SCL, AS5600_SDA, data_save, last_total_distance, LoadSettings(), MC_AS5600, mc_save, MOTOR_INVERT_CH1, MOTOR_INVERT_CH2, MOTOR_INVERT_CH3, MOTOR_INVERT_CH4, motors, and Hardware::PWM_Init().
Referenced by ControlLogic::MOTOR_PID::MOTOR_PID(), and setup().
InitBootCheck()
BootMode ControlLogic::InitBootCheck ()
Check Boot Mode (Button Press at Startup).
Reading ADC of sensor keys. If all are pressed (< 1.3V) at startup, toggle the boot mode (Klipper <-> BambuBus).
Returns
BootMode The active boot mode.
Definition at line 904 of file ControlLogic.cpp.
                             {
        // Read Sensors (Already inited in Hardware::Init)
        MC_PULL_ONLINE_read();
        
        bool all_pressed = true;
        for(int i=0; i<4; i++) {
             // User requested < 1.3V for mode switch.
             if (MC_PULL_stu_raw[i] > 1.3f) {
                 all_pressed = false;
                 break;
             }
        }
        
        if (all_pressed) {
            // Toggle Mode
            if (data_save.boot_mode == (uint32_t)BootMode::BambuBus) {
                data_save.boot_mode = (uint32_t)BootMode::Klipper;
            } else {
                data_save.boot_mode = (uint32_t)BootMode::BambuBus;
            }
            SetNeedToSave();
        }
        
        return (BootMode)data_save.boot_mode;
    }
References BambuBus, data_save, Klipper, MC_PULL_ONLINE_read(), MC_PULL_stu_raw, and SetNeedToSave().
Referenced by setup().
LoadSettings()
void ControlLogic::LoadSettings ()
Load settings from Flash memory.
If flash is invalid (CRC/Version mismatch), loads defaults.
Definition at line 847 of file ControlLogic.cpp.
                        {
        flash_save_struct *ptr = (flash_save_struct *)(use_flash_addr);
        if ((ptr->check == 0x40614061) && (ptr->version == Bambubus_version)) {
            memcpy(&data_save, ptr, sizeof(data_save));
        } else {
            // Default constants
            data_save.filament[0].color_R = 0xFF;
            data_save.boot_mode = (uint32_t)BootMode::BambuBus; // Default to BambuBus
            SetNeedToSave(); // Valid version but mismatch or invalid, save new defaults
        }
        
        Motion_control_save_struct *mc_ptr = (Motion_control_save_struct *)(Motion_control_save_flash_addr);
        if (mc_ptr->check == 0x40614061) {
            memcpy(&mc_save, mc_ptr, sizeof(mc_save));
        }
    }
References BambuBus, Bambubus_version, flash_save_struct::check, Motion_control_save_struct::check, data_save, mc_save, Motion_control_save_flash_addr, SetNeedToSave(), use_flash_addr, and flash_save_struct::version.
Referenced by Init().
MC_PULL_ONLINE_read()
void ControlLogic::MC_PULL_ONLINE_read ()
Read Analog Sensors and Update State.
Reads ADC values for Filament sensors and Voltage monitors. Updates MC_PULL_stu (pressure state) and MC_ONLINE_key_stu (filament presence). Also updates internal UnitState flags based on these readings.
Definition at line 240 of file ControlLogic.cpp.
                               {
        float *data = Hardware::ADC_GetValues();
        if (!data) return;
        MC_PULL_stu_raw[3] = data[0];
        MC_ONLINE_key_stu_raw[3] = data[1];
        MC_PULL_stu_raw[2] = data[2];
        MC_ONLINE_key_stu_raw[2] = data[3];
        MC_PULL_stu_raw[1] = data[4];
        MC_ONLINE_key_stu_raw[1] = data[5];
        MC_PULL_stu_raw[0] = data[6];
        MC_ONLINE_key_stu_raw[0] = data[7];
        for (int i = 0; i < 4; i++) {
            if (MC_PULL_stu_raw[i] > PULL_voltage_up) MC_PULL_stu[i] = 1;
            else if (MC_PULL_stu_raw[i] < PULL_voltage_down) MC_PULL_stu[i] = -1;
            else MC_PULL_stu[i] = 0;
            if (is_two == false) {
                if (MC_ONLINE_key_stu_raw[i] > 1.65f) MC_ONLINE_key_stu[i] = 1;
                else if (MC_ONLINE_key_stu_raw[i] < 1.55f) MC_ONLINE_key_stu[i] = 0;
            } else {
                if (MC_ONLINE_key_stu_raw[i] < 0.6f) MC_ONLINE_key_stu[i] = 0;
                else if (MC_ONLINE_key_stu_raw[i] < 1.4f) MC_ONLINE_key_stu[i] = 3;
                else if (MC_ONLINE_key_stu_raw[i] > 1.7f) MC_ONLINE_key_stu[i] = 1;
                else MC_ONLINE_key_stu[i] = 2;
            }
            
            // Sync status
            if (MC_ONLINE_key_stu[i] != 0) {
                 if (data_save.filament[i].status == AMS_filament_status::offline) {
                     data_save.filament[i].status = AMS_filament_status::online;
                 }
            } else {
                 data_save.filament[i].status = AMS_filament_status::offline;
            }
            
            // Update pressure (voltage in mV)
            data_save.filament[i].pressure = (uint16_t)(MC_PULL_stu_raw[i] * 1000.0f);
        }
    }
References Hardware::ADC_GetValues(), data_save, is_two, MC_ONLINE_key_stu, MC_ONLINE_key_stu_raw, MC_PULL_stu, MC_PULL_stu_raw, offline, online, PULL_voltage_down, and PULL_voltage_up.
Referenced by InitBootCheck(), and Run().
motor_motion_switch()
void ControlLogic::motor_motion_switch ()
State Machine for BambuBus Logic.
Manages transitions between filament states (Idle, Loading, Unloading, Using, Sending). Implements Load/Unload logic completion checks (Pressure/Distance).
Definition at line 962 of file ControlLogic.cpp.
    {
        int num = data_save.BambuBus_now_filament_num;
        uint16_t device_type = device_type_addr;
        for (int i = 0; i < 4; i++)
        {
            // Klipper Override: Do not interfere if we are in velocity control mode OR explicit auto-feed
            if (motors[i].motion == filament_motion_enum::velocity_control) continue;
            if (motors[i].motion == filament_motion_enum::pressure_ctrl_in_use) continue;
            if (i != num)
            {
                filament_now_position[i] = filament_idle;
                motors[i].SetMotion(filament_motion_enum::pressure_ctrl_idle);
            }
            else
            {
                // Has filament or not, we check for overrides first
                if (filament_now_position[num] == filament_unloading) {
                    // --- UNLOAD LOGIC ---
                    // If -1, we wait for sensor to clear (which happens in MC_ONLINE_key_stu)
                    // If sensor clear (0), we are done.
                    
                    bool done = false;
                    
                    if (unload_target_dist[num] == -1) {
                         // Unload until clear (Offline)
                         if (MC_ONLINE_key_stu[num] == 0) done = true;
                    } else {
                         // Unload distance
                         if (last_total_distance[num] >= (float)unload_target_dist[num]) done = true;
                         
                    }
                    if (done) {
                        motors[num].SetMotion(filament_motion_enum::stop);
                        filament_now_position[num] = filament_idle;
                        is_backing_out = false;
                        
                         // ACK Confirmation
                        char msg[64];
                        if (unload_target_dist[num] == -1) sprintf(msg, "\r\nUNLOAD_FILAMENT: OK (Tray %d, Clear)\r\n", num);
                        else sprintf(msg, "\r\nUNLOAD_FILAMENT: OK (Tray %d, Dist)\r\n", num);
                        Hardware::UART_Send((const uint8_t*)msg, strlen(msg));
                        return; // Done
                    }
                    
                    // IF NOT DONE, we just return to keep pulling?
                    // We need to ensure we don't fall through to other logic.
                    // But if sensor clears, done becomes true above.
                    // If sensor is still 1, we return here to avoid "in_use" logic interfering.
                    return;
                }
                if (MC_ONLINE_key_stu[num] == 1 || MC_ONLINE_key_stu[num] == 3) // Has filament
            {
                AMS_filament_motion current_motion = data_save.filament[num].motion_set;
                
                // --- LOAD FILAMENT OVERRIDE ---
                if (filament_now_position[num] == filament_loading) {
                    float pressure = MC_PULL_stu_raw[num];
                    
                    // Temporary Debug
                    static uint64_t last_dbg = 0;
                    if (Hardware::GetTime() - last_dbg > 500) {
                        char d[64]; sprintf(d, "\r\nLOAD P%d\r\n", num);
                        Hardware::UART_Send((const uint8_t*)d, strlen(d));
                        last_dbg = Hardware::GetTime();
                    }
                    
                    bool dist_done = false;
                    if (unload_target_dist[num] > 0) { // Using this var for load len too
                        if (last_total_distance[num] >= (float)unload_target_dist[num]) {
                            dist_done = true;
                        }
                    }
                    if (pressure > PULL_voltage_up) {
                        // Upper Limit Reached -> Success (Reached Toolhead?)
                        filament_now_position[num] = filament_using;
                        pull_state_old = true; // Set for pressure_ctrl
                        motors[num].SetMotion(filament_motion_enum::pressure_ctrl_in_use);
                        
                        // ACK Confirmation
                        char msg[64];
                        sprintf(msg, "\r\nLOAD_FILAMENT: OK (Tray %d, Pressure)\r\n", num);
                        Hardware::UART_Send((const uint8_t*)msg, strlen(msg));
                    }
                    else if (dist_done) {
                        // Distance Reached -> Done (Feed operation complete)
                        // Should we go to IDLE? Or USING?
                        // Plan said IDLE if distance reached without pressure.
                        filament_now_position[num] = filament_idle;
                        motors[num].SetMotion(filament_motion_enum::pressure_ctrl_idle);
                        is_backing_out = false; // Stop tracking
                        
                         // ACK Confirmation
                        char msg[64];
                        sprintf(msg, "\r\nLOAD_FILAMENT: OK (Tray %d, Dist)\r\n", num);
                        Hardware::UART_Send((const uint8_t*)msg, strlen(msg));
                    }
                    else if (pressure > 1.70f) {
                        // Pressure starting to change/limit approaching (1.85V Max) - Slow Down
                        motors[num].SetMotion(filament_motion_enum::slow_send);
                    }
                    else {
                        // Regular Feed
                        motors[num].SetMotion(filament_motion_enum::send);
                    }
                    return; // Skip standard switch
                }
                
                switch (current_motion)
                {
                case AMS_filament_motion::need_send_out:
                     Hardware::LED_SetColor(num, 0, 0, 255, 0);
                    filament_now_position[num] = filament_sending_out;
                    motors[num].SetMotion(filament_motion_enum::send);
                    break;
                    
                case AMS_filament_motion::need_pull_back:
                    pull_state_old = false;
                    is_backing_out = true;
                    filament_now_position[num] = filament_pulling_back;
                    if (device_type == BambuBus_AMS_lite) {
                        motors[num].SetMotion(filament_motion_enum::pull);
                    }
                    break;
                    
                case AMS_filament_motion::before_pull_back:
                case AMS_filament_motion::in_use:
                {
                    static uint64_t time_end = 0;
                    uint64_t time_now = get_time64();
                    
                    if (filament_now_position[num] == filament_sending_out)
                    {
                        is_backing_out = false;
                        pull_state_old = true;
                        filament_now_position[num] = filament_using;
                        time_end = time_now + 1500;
                    }
                    else if (filament_now_position[num] == filament_using)
                    {
                        last_total_distance[i] = 0;
                        if (time_now > time_end)
                        {
                             Hardware::LED_SetColor(num, 0, 255, 255, 255);
                            motors[num].SetMotion(filament_motion_enum::pressure_ctrl_in_use);
                        }
                        else
                        {
                            Hardware::LED_SetColor(num, 0, 128, 192, 128);
                            motors[num].SetMotion(filament_motion_enum::slow_send);
                        }
                    }
                    break;
                }
                case AMS_filament_motion::idle:
                    filament_now_position[num] = filament_idle;
                    motors[num].SetMotion(filament_motion_enum::pressure_ctrl_idle);
                    for (int j = 0; j < 4; j++)
                    {
                        if (MC_ONLINE_key_stu[j] == 1 || MC_ONLINE_key_stu[j] == 0) {
                             Hardware::LED_SetColor(j, 0, 0, 0, 255); // Blue
                        } else if (MC_ONLINE_key_stu[j] == 2) {
                             Hardware::LED_SetColor(j, 0, 255, 144, 0); // Orange
                        } else if (MC_ONLINE_key_stu[j] == 3) {
                             Hardware::LED_SetColor(j, 0, 0, 255, 255); // Cyan
                        }
                    }
                    break;
                }
            }
            else if (MC_ONLINE_key_stu[num] == 0) // No filament
            {
                filament_now_position[num] = filament_idle;
                motors[num].SetMotion(filament_motion_enum::pressure_ctrl_idle);
            }
            } // Close the Main Else
        }
    }
References BambuBus_AMS_lite, before_pull_back, data_save, device_type_addr, filament_idle, filament_loading, filament_now_position, filament_pulling_back, filament_sending_out, filament_unloading, filament_using, get_time64(), Hardware::GetTime(), idle, in_use, is_backing_out, last_total_distance, Hardware::LED_SetColor(), MC_ONLINE_key_stu, MC_PULL_stu_raw, motors, need_pull_back, need_send_out, pressure_ctrl_idle, pressure_ctrl_in_use, pull, pull_state_old, PULL_voltage_up, send, slow_send, stop, Hardware::UART_Send(), unload_target_dist, and velocity_control.
Referenced by Run().
MoveAxis()
void ControlLogic::MoveAxis (int axis, float dist_mm, float speed)
Manually move an axis (Klipper Primitive).
Uses Velocity Control mode to move a specific distance at a specific speed.
Parameters
axis Axis index (0-3).
dist_mm Distance to move (positive).
speed Speed in mm/s.
Definition at line 616 of file ControlLogic.cpp.
                                                        {
        if(axis < 0 || axis >= 4) return;
        
        // Use Velocity Control
        motors[axis].target_velocity = speed;
        motors[axis].target_distance = fabs(dist_mm); // Ensure positive
        motors[axis].SetMotion(filament_motion_enum::velocity_control);
    }
References motors, and velocity_control.
Referenced by KlipperCLI::HandleMove().
Prepare_For_filament_Pull_Back()
bool ControlLogic::Prepare_For_filament_Pull_Back (float_t OUT_filament_meters)
Check if pullback is required (Smart Pullback Logic).
If a lane is in filament_pulling_back state, this checks if it has reached the target distance (OUT_filament_meters). Stops it if so.
Parameters
OUT_filament_meters Target distance.
Returns
true If any lane is actively pulling back.
false If no lanes are pulling back.
Definition at line 751 of file ControlLogic.cpp.
    {
        bool wait = false;
        for (int i = 0; i < 4; i++)
        {
            if (filament_now_position[i] == filament_pulling_back)
            {
                if (last_total_distance[i] < OUT_filament_meters)
                {
                    motors[i].SetMotion(filament_motion_enum::pull);
                    
                    float npercent = (last_total_distance[i] / OUT_filament_meters) * 100.0f;
                    int r = 255 - ((255 / 100) * npercent);
                    int g = 125 - ((125 / 100) * npercent);
                    int b = (255 / 100) * npercent;
                    if(r<0) r=0;
                    if(g<0) g=0;
                    if(b<0) b=0;
                    Hardware::LED_SetColor(i, 0, r, g, b);
                }
                else
                {
                    is_backing_out = false;
                    motors[i].SetMotion(filament_motion_enum::stop);
                    filament_now_position[i] = filament_idle;
                    data_save.filament[i].motion_set = AMS_filament_motion::idle;
                    last_total_distance[i] = 0;
                }
                wait = true;
            }
        }
        return wait;
    }
References data_save, filament_idle, filament_now_position, filament_pulling_back, idle, is_backing_out, last_total_distance, Hardware::LED_SetColor(), motors, pull, and stop.
Referenced by Run().
ProcessHeartbeat()
void ControlLogic::ProcessHeartbeat (uint8_t * buffer, uint16_t length)
Handler for Heartbeat (0x20).
Updates connectivity timestamp.
Definition at line 1355 of file ControlLogic.cpp.
                                                            {
        UpdateConnectivity(true);
    }
References UpdateConnectivity().
ProcessLongPacket()
void ControlLogic::ProcessLongPacket (struct long_packge_data & data)
Handler/Dispatcher for Long Packets.
Processes parsed long packets based on their type (0x211, 0x218, 0x103, etc.).
Parameters
data Reference to parsed long_packge_data.
Definition at line 1435 of file ControlLogic.cpp.
                                                          {
        // switch data.type...
        // 0x211 Read Filament -> Send Response
        // 0x218 Set Filament -> Update & Send ACK
        // 0x103 Version -> Send Response
        
        // This function executes the Logic for Long Packets.
        // It uses "SendPacket" to send replies.
        
        // Implementation omitted for brevity but should be here.
        // ...
    }
Referenced by CommandRouter::HandleLongPacket().
ProcessMotionLong()
void ControlLogic::ProcessMotionLong (uint8_t * buffer, uint16_t length)
Handler for Filament Motion Long packet (0x04).
Note
Currently a placeholder.
Definition at line 1302 of file ControlLogic.cpp.
                                                             {
        // Just forward for now or implement logic if found
    }
ProcessMotionLongLogic()
void ControlLogic::ProcessMotionLongLogic (uint8_t * payload, uint16_t length)
ProcessMotionShort()
void ControlLogic::ProcessMotionShort (uint8_t * buffer, uint16_t length)
Handler for Filament Motion Short packet (0x03).
Extracts arguments from the buffer and calls ProcessMotionShortLogic.
Definition at line 1285 of file ControlLogic.cpp.
                                                              {
        if (length < 9) return;
        // Parse Args
        uint8_t ams_num = buffer[5];
        if (ams_num != 0) return;
        uint8_t statu_flags = buffer[6];
        uint8_t read_num = buffer[7];
        uint8_t motion_flag = buffer[8];
        
        ProcessMotionShortLogic(ams_num, statu_flags, read_num, motion_flag);
    }
References ProcessMotionShortLogic().
ProcessMotionShortLogic()
void ControlLogic::ProcessMotionShortLogic (uint8_t ams_num, uint8_t statu_flags, uint8_t read_num, uint8_t fliment_motion_flag)
Core logic for processing Short Motion packets.
Handles state transitions based on status flags received from the printer. Updates filament meter usage, pressure status, and responds with the current status.
Parameters
ams_num AMS Unit ID (0-3).
statu_flags Status bitmask.
read_num Filament/Tray index interacting.
fliment_motion_flag Motion control flags.
Definition at line 1160 of file ControlLogic.cpp.
                                                                                                                      {
        // Core Logic from ProcessMotionShort
        
        static uint64_t time_last = 0;
        uint64_t time_now = get_time64();
        uint64_t time_used = time_now - time_last;
        time_last = time_now;
        if (device_type_addr == BambuBus_AMS) { // AMS08
             if (read_num < 4) {
                 FilamentState &f = data_save.filament[read_num];
                 
                 if ((statu_flags == 0x03) && (fliment_motion_flag == 0x00)) { // 03 00
                     if (data_save.BambuBus_now_filament_num != read_num) {
                         if (data_save.BambuBus_now_filament_num < 4) {
                             data_save.filament[data_save.BambuBus_now_filament_num].motion_set = AMS_filament_motion::idle;
                             data_save.filament_use_flag = 0x00;
                             data_save.filament[data_save.BambuBus_now_filament_num].pressure = 0xFFFF;
                         }
                         data_save.BambuBus_now_filament_num = read_num;
                     }
                     f.motion_set = AMS_filament_motion::need_send_out;
                     data_save.filament_use_flag = 0x02;
                     f.pressure = 0x4700;
                 }
                 else if (statu_flags == 0x09) { // 09 A5 / 09 3F
                      if (f.motion_set == AMS_filament_motion::need_send_out) {
                          f.motion_set = AMS_filament_motion::in_use;
                          data_save.filament_use_flag = 0x04;
                          f.meters_virtual_count = 0;
                      }
                      else if (f.meters_virtual_count < 10000) {
                          f.meters += (float)time_used / 300000;
                          f.meters_virtual_count += time_used;
                      }
                      f.pressure = 0x2B00;
                 }
                 else if ((statu_flags == 0x07) && (fliment_motion_flag == 0x7F)) { // 07 7F
                      f.motion_set = AMS_filament_motion::in_use;
                      data_save.filament_use_flag = 0x04;
                      f.pressure = 0x2B00;
                 }
             }
             else if (read_num == 0xFF) {
                 if ((statu_flags == 0x03) && (fliment_motion_flag == 0x00)) { // 03 00(FF)
                     if (data_save.BambuBus_now_filament_num < 4) {
                         FilamentState &f = data_save.filament[data_save.BambuBus_now_filament_num];
                         if (f.motion_set == AMS_filament_motion::in_use) {
                             f.motion_set = AMS_filament_motion::need_pull_back;
                             data_save.filament_use_flag = 0x02;
                         }
                         f.pressure = 0x4700;
                     }
                 } else {
                     for(int i=0; i<4; i++) {
                         if(data_save.filament[i].motion_set != AMS_filament_motion::idle) {
                             data_save.filament[i].motion_set = AMS_filament_motion::idle;
                         }
                     }
                     data_save.BambuBus_now_filament_num = 0xFF;
                     data_save.filament_use_flag = 0x00;
                 }
             }
        }
        
        // Respond
        // IMPORTANT: We need to send a response. The response format handles details.
        // We will construct the default response payload here.
        // Or call utility?
        
        // [PAYLOAD: AMS_NUM(0), flags(8), filament_left_char(1), 00, 00, 00, 00, 00, 00, 00]
        // Length around 10.
        // Helper needed.
        uint8_t res_buf[14];
        memset(res_buf, 0, 14);
        res_buf[0] = ams_num; // 0
        
        // Byte 1: Flags of some sort?
        // Original: package_send_short logic used constant array C_test?
        // No, C_test was #define.
        // BambuBus.cpp logic was lost in previous turn but snippet in ControlLogic.cpp showed some logic.
        // Let's assume response is simple status.
        
        // Byte 1: 0x80 | (0x4 if data_save.filament_use_flag & 0x02?)
        // Let's simplified response based on observation:
        res_buf[1] = 0x80;
        if (data_save.filament_use_flag & 0x02) res_buf[1] |= 0x04;
        
        // Byte 2: Filament Left Char (Bitmask)
        uint8_t filament_left = 0;
         for (int i = 0; i < 4; i++) {
             if (data_save.filament[i].status == AMS_filament_status::online) {
                 filament_left |= (0x1 << (2*i));
                 if (device_type_addr == BambuBus_AMS) {
                     if (data_save.filament[i].motion_set != AMS_filament_motion::idle) {
                         filament_left |= (0x2 << (2*i));
                     }
                 }
             }
         }
        res_buf[2] = filament_left;
        
        // Send Packet Wrapper
        // We need a way to send the packet.
        // Create a buffer for CommandRouter::SendPacket
        uint8_t packet[32];
        packet[0] = 0x3D; packet[1] = 0xC5;
        packet[4] = 0x03; // CMD (Echoing command type? Or Res type?)
        // If Request was 0x03, Response is 0x03? Check logs.
        // Usually Motion Short response is same Command ID with different data.
        
        packet[2] = 10 + 5; // LEN
        memcpy(packet+5, res_buf, 10);
        
        uint16_t len = 15;
        BambuBusProtocol::BuildPacketWithCRC(packet, len);
        CommandRouter::SendPacket(packet, len);
    }
References BambuBus_AMS, BambuBusProtocol::BuildPacketWithCRC(), data_save, device_type_addr, get_time64(), idle, in_use, FilamentState::meters, FilamentState::meters_virtual_count, FilamentState::motion_set, need_pull_back, need_send_out, online, FilamentState::pressure, and CommandRouter::SendPacket().
Referenced by ProcessMotionShort().
ProcessOnlineDetect()
void ControlLogic::ProcessOnlineDetect (uint8_t * buffer, uint16_t length)
Handler for Online Detect (0x05).
Responds with the Online (0x05) packet to announce presence to the printer.
Definition at line 1311 of file ControlLogic.cpp.
                                                               {
         // Respond 0x05
         // uint8_t res[1]; // Unused
         // res[0] = 0x00;
         
         // 3D C5 LEN CRC8 CMD(05) Payload...
         uint8_t packet[32];
         packet[0] = 0x3D; packet[1] = 0xC5;
         packet[4] = 0x05;
         
         // Payload currently nothing?
         // Original code sent 1 byte payload?
         packet[5] = 0x00; // AMS number?
         
         uint16_t len = 6; // Header(5) + Payload(1)
         packet[2] = len;
         
         BambuBusProtocol::BuildPacketWithCRC(packet, len);
         CommandRouter::SendPacket(packet, len);
         UpdateConnectivity(true);
    }
References BambuBusProtocol::BuildPacketWithCRC(), CommandRouter::SendPacket(), and UpdateConnectivity().
ProcessREQx6()
void ControlLogic::ProcessREQx6 (uint8_t * buffer, uint16_t length)
Handler for REQx6 (0x06).
Responds with a simple ACK (0x06).
Definition at line 1338 of file ControlLogic.cpp.
                                                        {
        // Just ACK with 0x06
        uint8_t packet[32];
        packet[0] = 0x3D; packet[1] = 0xC5;
        packet[4] = 0x06;
        packet[5] = 0x00;
        uint16_t len = 6;
        packet[2] = len;
        BambuBusProtocol::BuildPacketWithCRC(packet, len);
        CommandRouter::SendPacket(packet, len);
    }
References BambuBusProtocol::BuildPacketWithCRC(), and CommandRouter::SendPacket().
ProcessSetFilamentInfo()
void ControlLogic::ProcessSetFilamentInfo (uint8_t * buffer, uint16_t length)
Handler for Set Filament Info (0x08 - Short).
Decodes payload and calls SetFilamentInfoAction.
Definition at line 1364 of file ControlLogic.cpp.
                                                                  {
        // Short Packet Set Filament Info (0x08)
        // Offset 5 is start of payload.
        // Logic from original:
        // buffer[5] = AMS num?
        // buffer[6] = Filament Index?
        // buffer[7]... color?
        // Let's assume payload matches SetFilamentInfoAction args.
        
        if (length < 10) return;
        // uint8_t tray_index = buffer[5]; // Unused warning fix
        // Wait, normally payload is: [AMS_Num] [Tray_Num] [R] [G] [B] [A] ...
        // Needs verifying protocol.
        // Assuming:
        int id = buffer[5]; // If direct tray mapping
        if (id >= 4) return;
        
        FilamentInfo info;
        // Populate info from buffer...
        
        // Call Action
        SetFilamentInfoAction(id, info);
        
        // Send ACK (0x08)
        // ...
    }
References SetFilamentInfoAction().
Run()
void ControlLogic::Run ()
Main Control Loop.
Called repeatedly from main. Checks sensors, manages logic switching, updates motor control, handles LED updates, and manages Flash saving.
Definition at line 792 of file ControlLogic.cpp.
               {
        static uint64_t last_run = 0;
        uint64_t now = Hardware::GetTime();
        float time_E = (now - last_run) / 1000.0f;
        last_run = now;
        
        MC_PULL_ONLINE_read();
        AS5600_Update(time_E);
        
        if (Bambubus_need_to_save) {
            if (now - save_timer > 500) {
                SaveSettings();
            }
        }
        
        bool pulling = Prepare_For_filament_Pull_Back(P1X_OUT_filament_meters);
        
        if (!pulling) {
            motor_motion_switch();
        }
        
        for(int i=0; i<4; i++) {
            motors[i].Run(time_E);
        }
        
        // System LED Debug Flash
        static uint64_t last_led_update = 0;
        if (now - last_led_update > 1000) {
             static bool toggle = false;
             toggle = !toggle;
             // Heartbeat color: Green for BambuBus, White for Klipper
             if (toggle) {
                 if (data_save.boot_mode == (uint32_t)BootMode::Klipper) {
                     Hardware::LED_SetColor(4, 0, 10, 10, 10); // White
                 } else {
                     Hardware::LED_SetColor(4, 0, 0, 10, 0); // Green
                 }
             }
             else Hardware::LED_SetColor(4, 0, 0, 0, 0);
             last_led_update = now;
        }
        // Update LED physical output at ~20Hz to prevent blocking interrupts too often
        static uint64_t last_led_show_time = 0;
        if (now - last_led_show_time > 50) {
             Hardware::LED_Show();
             last_led_show_time = now;
        }
    }
References AS5600_Update(), Bambubus_need_to_save, data_save, Hardware::GetTime(), Klipper, Hardware::LED_SetColor(), Hardware::LED_Show(), MC_PULL_ONLINE_read(), motor_motion_switch(), motors, P1X_OUT_filament_meters, Prepare_For_filament_Pull_Back(), save_timer, and SaveSettings().
Referenced by loop().
SaveSettings()
void ControlLogic::SaveSettings ()
Commit settings to Flash memory.
Writes the current data_save struct to flash.
Definition at line 722 of file ControlLogic.cpp.
                        {
        Flash_saves(&data_save, sizeof(data_save), use_flash_addr);
        Bambubus_need_to_save = false;
    }
References Bambubus_need_to_save, data_save, Flash_saves(), and use_flash_addr.
Referenced by Run().
SetAutoFeed()
void ControlLogic::SetAutoFeed (int lane, bool enable)
Enable/Disable Auto-Feed (Pressure Control) for a lane.
Parameters
lane Lane index.
enable True to enable, False to stop.
Definition at line 643 of file ControlLogic.cpp.
                                            {
        if(lane < 0 || lane >= 4) return;
        
        if (enable) {
             motors[lane].SetMotion(filament_motion_enum::pressure_ctrl_in_use);
             // We may need to ensure filament_now_position isn't overwriting this?
             // Actually, motor_motion_switch checks motor[i].motion, so we should be good if we add check there.
        } else {
             motors[lane].SetMotion(filament_motion_enum::stop);
             filament_now_position[lane] = filament_idle;
        }
    }
References filament_idle, filament_now_position, motors, pressure_ctrl_in_use, and stop.
Referenced by KlipperCLI::HandleSetAutoFeed().
SetFilamentInfoAction()
void ControlLogic::SetFilamentInfoAction (int id, const FilamentInfo & info, float meters)
Action helper to update filament metadata.
Updates Color, Type, ID, Temps, etc. for a specific tray. Triggers a Flash Save.
Parameters
id Tray ID.
info Info structure.
meters Odometer reading (optional, -1 to ignore).
Definition at line 1401 of file ControlLogic.cpp.
                                                                               {
        if (id < 0 || id >= 4) return;
        
        FilamentState &target = data_save.filament[id];
        
        // Copy Basic Fields
        memcpy(target.ID, info.ID, sizeof(target.ID));
        memcpy(target.name, info.name, sizeof(target.name));
        target.color_R = info.color_R;
        target.color_G = info.color_G;
        target.color_B = info.color_B;
        target.color_A = info.color_A;
        target.temperature_min = info.temperature_min;
        target.temperature_max = info.temperature_max;
        
        if (meters >= 0) {
             target.meters = meters;
        }
        // Ensure strings are null terminated just in case
        target.ID[7] = 0;
        target.name[19] = 0;
        
        SetNeedToSave();
    }
References FilamentInfo::color_A, FilamentInfo::color_B, FilamentInfo::color_G, FilamentInfo::color_R, data_save, FilamentInfo::ID, FilamentState::meters, FilamentInfo::name, SetNeedToSave(), FilamentInfo::temperature_max, and FilamentInfo::temperature_min.
Referenced by KlipperCLI::HandleSetFilamentInfo(), and ProcessSetFilamentInfo().
SetNeedToSave()
void ControlLogic::SetNeedToSave ()
Flag that settings need to be saved.
Sets a dirty flag and resets the save timer (debounce).
Definition at line 733 of file ControlLogic.cpp.
                         {
        if (!Bambubus_need_to_save) {
             Bambubus_need_to_save = true;
             save_timer = Hardware::GetTime();
        }
    }
References Bambubus_need_to_save, Hardware::GetTime(), and save_timer.
Referenced by InitBootCheck(), LoadSettings(), and SetFilamentInfoAction().
StartLoadFilament()
void ControlLogic::StartLoadFilament (int tray, int length_mm)
Initiate a Filament Load sequence for a specific tray.
Sets the state machine to filament_loading, initializes variables, and sets motor to send.
Parameters
tray Tray index (0-3).
length_mm Target length in mm (if > 0, stops at distance; otherwise uses pressure logic).
Definition at line 529 of file ControlLogic.cpp.
                                                    {
        if (tray < 0 || tray >= 4) return;
        
        // Setup state
        data_save.BambuBus_now_filament_num = tray;
        data_save.filament_use_flag = 0x02;
        
        filament_now_position[tray] = filament_loading;
        motors[tray].SetMotion(filament_motion_enum::send); // Start fast
        
        unload_target_dist[tray] = length_mm; // Reuse this variable for target distance
        
        // Reset distance tracking if we are using length
        if (length_mm > 0) {
            is_backing_out = true; // Use backing out flag to enable distance accumulation in Run()?
            // Wait, Run() only accumulates if "is_backing_out" is true?
            // "if (is_backing_out) last_total_distance += ..."
            // Yes. So we need to set is_backing_out = true even for loading if we want distance.
            // But verify if "StartUnloadFilament" clears it? StartUnload sets it true.
            // We should ensure Run() logic supports positive distance accumulation too if speed is positive?
            // Run() uses fabs(speed * time). So direction doesn't matter for accumulation.
            
            last_total_distance[tray] = 0;
            is_backing_out = true;
        } else {
             is_backing_out = false; // Normal load doesn't track distance usually?
             // Actually, regular load uses Pressure surveillance logic.
        }
        // Ensure others are idle
        for(int i=0; i<4; i++) {
            if(i != tray) {
               filament_now_position[i] = filament_idle;
               motors[i].SetMotion(filament_motion_enum::pressure_ctrl_idle);
            }
        }
    }
References data_save, filament_idle, filament_loading, filament_now_position, is_backing_out, last_total_distance, motors, pressure_ctrl_idle, send, and unload_target_dist.
StartUnloadFilament()
void ControlLogic::StartUnloadFilament (int tray, int length_mm)
Initiate a Filament Unload sequence for a specific tray.
Sets state to filament_unloading.
Parameters
tray Tray index (0-3).
length_mm Target distance to unload (or -1 to unload until sensor clear).
Definition at line 576 of file ControlLogic.cpp.
                                                      {
        if (tray < 0 || tray >= 4) return;
        
        // Setup state
        data_save.BambuBus_now_filament_num = tray;
        data_save.filament_use_flag = 0x02; // Busy/Moving
        
        filament_now_position[tray] = filament_unloading;
        motors[tray].SetMotion(filament_motion_enum::pull); // Start Pulling
        
        unload_target_dist[tray] = length_mm;
        unload_start_meters[tray] = last_total_distance[tray]; // Capture start pos (using accumulated dist logic if valid or need tracking)
        // Actually last_total_distance is used for pullback accumulation?
        // Let's reset last_total_distance logic or use a new tracker?
        // Existing "Prepare_For_filament_Pull_Back" uses "last_total_distance" which accumulates in Run() if "is_backing_out" is true.
        
        is_backing_out = true;
        last_total_distance[tray] = 0; // Reset counter for this op
        
        // Ensure others are idle
        for(int i=0; i<4; i++) {
            if(i != tray) {
               filament_now_position[i] = filament_idle;
               motors[i].SetMotion(filament_motion_enum::pressure_ctrl_idle);
            }
        }
    }
References data_save, filament_idle, filament_now_position, filament_unloading, is_backing_out, last_total_distance, motors, pressure_ctrl_idle, pull, unload_start_meters, and unload_target_dist.
StopAll()
void ControlLogic::StopAll ()
Stop all motors.
Definition at line 629 of file ControlLogic.cpp.
                   {
        for(int i=0; i<4; i++) {
             motors[i].SetMotion(filament_motion_enum::stop);
             filament_now_position[i] = filament_idle;
        }
    }
References filament_idle, filament_now_position, motors, and stop.
Referenced by KlipperCLI::HandleStop().
UpdateConnectivity()
void ControlLogic::UpdateConnectivity (bool online)
Update connectivity status (Online/Offline).
Resets Heartbeat timer.
Parameters
online Status.
Definition at line 948 of file ControlLogic.cpp.
                                         {
        is_connected = online;
        if (online) last_heartbeat_time = Hardware::GetTime();
    }
References Hardware::GetTime(), is_connected, last_heartbeat_time, and online.
Referenced by ProcessHeartbeat(), ProcessOnlineDetect(), CommandRouter::Route(), and CommandRouter::Run().
Variable Documentation
as5600_distance_save
int32_t ControlLogic::as5600_distance_save[4] = {0, 0, 0, 0} [static]
Definition at line 213 of file ControlLogic.cpp.
{0, 0, 0, 0};
Referenced by AS5600_Update().
Assist_send_filament
bool ControlLogic::Assist_send_filament[4] = {false} [static]
Definition at line 209 of file ControlLogic.cpp.
{false};
Referenced by ControlLogic::MotorChannel::Run().
Bambubus_need_to_save
bool ControlLogic::Bambubus_need_to_save = false [static]
Definition at line 223 of file ControlLogic.cpp.
Referenced by Run(), SaveSettings(), and SetNeedToSave().
filament_now_position
filament_now_position_enum ControlLogic::filament_now_position[4] = {filament_idle, filament_idle, filament_idle, filament_idle} [static]
Definition at line 220 of file ControlLogic.cpp.
{filament_idle, filament_idle, filament_idle, filament_idle};
Referenced by motor_motion_switch(), Prepare_For_filament_Pull_Back(), SetAutoFeed(), StartLoadFilament(), StartUnloadFilament(), and StopAll().
is_backing_out
bool ControlLogic::is_backing_out = false [static]
Definition at line 211 of file ControlLogic.cpp.
Referenced by motor_motion_switch(), Prepare_For_filament_Pull_Back(), ControlLogic::MotorChannel::Run(), StartLoadFilament(), and StartUnloadFilament().
is_two
const bool ControlLogic::is_two = true [static]
Definition at line 212 of file ControlLogic.cpp.
Referenced by MC_PULL_ONLINE_read(), and ControlLogic::MotorChannel::Run().
MC_ONLINE_key_stu
int ControlLogic::MC_ONLINE_key_stu[4] = {0, 0, 0, 0} [static]
Definition at line 208 of file ControlLogic.cpp.
{0, 0, 0, 0}; // 0:Off, 1:Online(Two), 2:ExTrip, 3:InTrip
Referenced by GetSensorState(), MC_PULL_ONLINE_read(), motor_motion_switch(), ControlLogic::MotorChannel::Run(), and ControlLogic::MotorChannel::UpdateLEDStatus().
MC_ONLINE_key_stu_raw
float ControlLogic::MC_ONLINE_key_stu_raw[4] = {0, 0, 0, 0} [static]
Definition at line 207 of file ControlLogic.cpp.
{0, 0, 0, 0};
Referenced by MC_PULL_ONLINE_read().
MC_PULL_stu
int ControlLogic::MC_PULL_stu[4] = {0, 0, 0, 0} [static]
Definition at line 206 of file ControlLogic.cpp.
{0, 0, 0, 0};
Referenced by MC_PULL_ONLINE_read(), ControlLogic::MotorChannel::Run(), and ControlLogic::MotorChannel::UpdateLEDStatus().
MC_PULL_stu_raw
float ControlLogic::MC_PULL_stu_raw[4] = {0, 0, 0, 0} [static]
Definition at line 205 of file ControlLogic.cpp.
{0, 0, 0, 0};
Referenced by ControlLogic::MotorChannel::GetXByPressure(), InitBootCheck(), MC_PULL_ONLINE_read(), motor_motion_switch(), and ControlLogic::MotorChannel::Run().
motors
MotorChannel ControlLogic::motors[4] = {0, 1, 2, 3} [static]
Definition at line 517 of file ControlLogic.cpp.
{0, 1, 2, 3};
Referenced by GetLaneMotion(), Init(), motor_motion_switch(), MoveAxis(), Prepare_For_filament_Pull_Back(), Run(), SetAutoFeed(), StartLoadFilament(), StartUnloadFilament(), and StopAll().
P1X_OUT_filament_meters
float_t ControlLogic::P1X_OUT_filament_meters = 200.0f
Definition at line 201 of file ControlLogic.cpp.
Referenced by Run().
pull_state_old
bool ControlLogic::pull_state_old = false [static]
Definition at line 210 of file ControlLogic.cpp.
Referenced by motor_motion_switch(), and ControlLogic::MotorChannel::Run().
PULL_voltage_down
float ControlLogic::PULL_voltage_down = 1.45f
Definition at line 197 of file ControlLogic.cpp.
Referenced by MC_PULL_ONLINE_read().
PULL_voltage_up
float ControlLogic::PULL_voltage_up = 1.85f
Definition at line 196 of file ControlLogic.cpp.
Referenced by MC_PULL_ONLINE_read(), and motor_motion_switch().
save_timer
uint64_t ControlLogic::save_timer = 0 [static]
Definition at line 224 of file ControlLogic.cpp.
Referenced by Run(), and SetNeedToSave().
speed_as5600
float ControlLogic::speed_as5600[4] = {0, 0, 0, 0} [static]
Definition at line 204 of file ControlLogic.cpp.
{0, 0, 0, 0};
Referenced by AS5600_Update(), and ControlLogic::MotorChannel::Run().
unload_start_meters
float ControlLogic::unload_start_meters[4] = {0, 0, 0, 0} [static]
Definition at line 217 of file ControlLogic.cpp.
{0, 0, 0, 0};
Referenced by StartUnloadFilament().
unload_target_dist
int32_t ControlLogic::unload_target_dist[4] = {0, 0, 0, 0} [static]
Definition at line 216 of file ControlLogic.cpp.
{0, 0, 0, 0}; // -1 for clear sensor
Referenced by motor_motion_switch(), StartLoadFilament(), and StartUnloadFilament().