KlipperCLI Namespace Reference
Functions
void SendResponse (JsonDocument &d)
Serialize and send a JSON response.
void SendError (int id, const char *code, const char *msg)
Helper to send an Error response.
void SendOk (int id, const char *code=nullptr, const char *msg=nullptr)
Helper to send a Success (OK) response.
void HandlePing (int id, JsonObject args)
Handler for PING command.
void HandleStatus (int id, JsonObject args)
Handler for STATUS command.
void HandleGetSensors (int id, JsonObject args)
Handler for GET_SENSORS command.
void HandleMove (int id, JsonObject args)
Handler for MOVE command.
void HandleStop (int id, JsonObject args)
Handler for STOP command.
void HandleSelectLane (int id, JsonObject args)
Handler for SELECT_LANE command.
void HandleSetAutoFeed (int id, JsonObject args)
Handler for SET_AUTO_FEED command.
void HandleGetFilamentInfo (int id, JsonObject args)
Handler for GET_FILAMENT_INFO command.
void HandleSetFilamentInfo (int id, JsonObject args)
Handler for SET_FILAMENT_INFO command.
void ProcessPacket (char *json_str)
Parse and Dispatch a JSON Packet.
void Init ()
Initialize Klipper CLI.
void Run ()
Main Execution Loop.
void FeedByte (uint8_t b)
Feed a byte into the RX buffer.
bool IsConnected ()
Variables
static char rx_buffer [1024]
static int rx_idx = 0
static JsonDocument doc
static volatile bool packet_ready = false
Function Documentation
FeedByte()
void KlipperCLI::FeedByte (uint8_t b)
Feed a byte into the RX buffer.
Accumlates bytes until a newline is found.
Parameters
b Byte to append.
Definition at line 467 of file KlipperCLI.cpp.
                             {
        // Prevent buffer overrun
        if (packet_ready) return;
        if (b == '\n' || b == '\r') {
             if (rx_idx > 0) {
                 rx_buffer[rx_idx] = '\0';
                 packet_ready = true;
             }
             // Ignore empty lines (e.g. \r then \n)
        } else {
            if (rx_idx < 1023) {
                rx_buffer[rx_idx++] = (char)b;
            } else {
                rx_idx = 0; // Overflow reset
            }
        }
    }
References packet_ready, rx_buffer, and rx_idx.
Referenced by CommandRouter::Init().
HandleGetFilamentInfo()
void KlipperCLI::HandleGetFilamentInfo (int id, JsonObject args)
Handler for GET_FILAMENT_INFO command.
Returns metadata for a specific lane.
Definition at line 305 of file KlipperCLI.cpp.
                                                        {
         if(!args["lane"].is<int>()) { SendError(id, "BAD_ARGS", "Missing lane"); return; }
         int lane = args["lane"];
         if(lane < 0 || lane >= 4) { SendError(id, "BAD_ARGS", "Invalid lane"); return; }
         
         FilamentState &f = UnitState::GetFilament(lane);
         
         static char output[1024];
         int offset = 0;
         
         // Safe Strings
         char safe_id[9]; memcpy(safe_id, f.ID, 8); safe_id[8]=0;
         char safe_name[21]; memcpy(safe_name, f.name, 20); safe_name[20]=0;
         
         // Color
         int r = f.color_R;
         int g = f.color_G;
         int b = f.color_B;
         int a = f.color_A;
         
         // Manual Float
         int m_int = (int)f.meters;
         int m_dec = (int)((f.meters - m_int) * 100);
         if(m_dec<0) m_dec = -m_dec;
         
         int p_int = f.pressure / 1000;
         int p_dec = f.pressure % 1000;
         
         offset += snprintf(output + offset, sizeof(output) - offset,
             "{\"id\":%d,\"cmd\":\"GET_FILAMENT_INFO\",\"ok\":true,\"info\":{\"lane\":%d,\"id_str\":\"%s\",\"name\":\"%s\",\"temp_min\":%d,\"temp_max\":%d,\"meters\":%d.%02d,\"pressure\":%d.%03d,\"color\":[%d,%d,%d,%d]}}\r\n",
             id, lane, safe_id, safe_name, f.temperature_min, f.temperature_max, m_int, m_dec, p_int, p_dec, r,g,b,a
         );
         
         Hardware::UART_Send((const uint8_t*)output, offset);
    }
References FilamentInfo::color_A, FilamentInfo::color_B, FilamentInfo::color_G, FilamentInfo::color_R, UnitState::GetFilament(), FilamentInfo::ID, FilamentState::meters, FilamentInfo::name, FilamentState::pressure, SendError(), FilamentInfo::temperature_max, FilamentInfo::temperature_min, and Hardware::UART_Send().
Referenced by ProcessPacket().
HandleGetSensors()
void KlipperCLI::HandleGetSensors (int id, JsonObject args)
Handler for GET_SENSORS command.
Returns a simple list of booleans indicating filament presence.
Definition at line 185 of file KlipperCLI.cpp.
                                                   {
         doc.clear();
         doc["id"] = id;
         doc["cmd"] = "GET_SENSORS";
         
         uint16_t state = ControlLogic::GetSensorState();
         JsonArray lanes = doc["lane"].to<JsonArray>();
         for(int i=0; i<4; i++) {
             lanes.add((state & (1<<i)) ? 1 : 0);
         }
         SendResponse(doc);
    }
References doc, ControlLogic::GetSensorState(), and SendResponse().
Referenced by ProcessPacket().
HandleMove()
void KlipperCLI::HandleMove (int id, JsonObject args)
Handler for MOVE command.
Initiates a velocity-controlled movement on a specific axis.
Parameters
axis "FEED", "SELECTOR", or "0"-"3".
dist_mm Distance to move (always positive).
speed Velocity in mm/s (mapped to motor units).
Definition at line 208 of file KlipperCLI.cpp.
                                             {
        // Args extracted before clearing doc
        // BUT wait, 'args' is a reference to 'doc' internals (if passed from ProcessPacket).
        // If we clear 'doc' inside HandleMove, 'args' becomes invalid!
        // CRITICAL BUG: accessing 'args' after doc.clear() would crash.
        // We MUST extract args BEFORE clearing doc.
        
        // However, we need to send OK/Error.
        // Option 1: Copy args.
        // Option 2: Use a SECOND static doc for Response?
        // Or Option 3: Use 'SendOk/SendError' which clears doc, AFTER using args.
        
        if(!args["axis"].is<const char*>() || !args["dist_mm"].is<float>() || !args["speed"].is<float>()) {
             SendError(id, "BAD_ARGS", "Missing axis, dist, or speed"); // Clears doc
             return;
        }
        
        // Copy values to stack variables
        char axis[16]; strncpy(axis, args["axis"], 15); axis[15]=0;
        float dist = args["dist_mm"];
        float speed = args["speed"];
        
        // Now safe to use logic that might call SendOk/SendError (clearing doc)
        
        int motor_idx = -1;
        if(strcmp(axis, "FEED") == 0) {
            motor_idx = UnitState::GetCurrentFilamentIndex();
        } else if(strcmp(axis, "SELECTOR") == 0) {
        } else if (strncmp(axis, "SPOOL", 5) == 0) {
        } else if (isdigit(axis[0])) {
             motor_idx = atoi(axis);
        }
        
        if (motor_idx >= 0 && motor_idx < 4) {
             ControlLogic::MoveAxis(motor_idx, dist, speed);
             SendOk(id, "MOVING", "Motion started");
        } else {
             SendError(id, "BAD_AXIS", "Invalid or unknown axis");
        }
    }
References UnitState::GetCurrentFilamentIndex(), ControlLogic::MoveAxis(), SendError(), and SendOk().
Referenced by ProcessPacket().
HandlePing()
void KlipperCLI::HandlePing (int id, JsonObject args)
Handler for PING command.
Returns telemetry (version, uptime).
Definition at line 90 of file KlipperCLI.cpp.
                                             {
        doc.clear();
        doc["id"] = id;
        doc["cmd"] = "PING";
        doc["result"] = "ok";
        
        JsonObject t = doc["telemetry"].to<JsonObject>();
        t["version"] = UnitState::GetVersion();
        t["uptime"] = Hardware::GetTime();
        
        SendResponse(doc);
    }
References doc, Hardware::GetTime(), UnitState::GetVersion(), and SendResponse().
Referenced by ProcessPacket().
HandleSelectLane()
void KlipperCLI::HandleSelectLane (int id, JsonObject args)
Handler for SELECT_LANE command.
Sets the active lane index.
Parameters
lane Lane index (0-3).
Definition at line 268 of file KlipperCLI.cpp.
                                                   {
        if(!args["lane"].is<int>()) {
            SendError(id, "BAD_ARGS", "Missing lane");
            return;
        }
        int lane = args["lane"];
        if(lane < 0 || lane >= 4) {
            SendError(id, "BAD_LANE", "Lane must be 0-3");
            return;
        }
        UnitState::SetCurrentFilamentIndex(lane);
        SendOk(id);
    }
References SendError(), SendOk(), and UnitState::SetCurrentFilamentIndex().
Referenced by ProcessPacket().
HandleSetAutoFeed()
void KlipperCLI::HandleSetAutoFeed (int id, JsonObject args)
Handler for SET_AUTO_FEED command.
Enables automatic pressure control (feeding/holding) for a lane.
Definition at line 288 of file KlipperCLI.cpp.
                                                    {
        if(!args["lane"].is<int>() || !args["enable"].is<bool>()) {
             SendError(id, "BAD_ARGS", "Missing lane or enable");
             return;
        }
        int lane = args["lane"];
        bool enable = args["enable"];
        ControlLogic::SetAutoFeed(lane, enable);
        SendOk(id);
    }
References SendError(), SendOk(), and ControlLogic::SetAutoFeed().
Referenced by ProcessPacket().
HandleSetFilamentInfo()
void KlipperCLI::HandleSetFilamentInfo (int id, JsonObject args)
Handler for SET_FILAMENT_INFO command.
Updates metadata for a specific lane. Supports partial updates.
Definition at line 347 of file KlipperCLI.cpp.
                                                        {
         // Need to extract ALL args to stack/struct before clearing doc
         // This is tricky for complex objects like Color array.
         // Actually, do we assume ProcessPacket uses the SAME 'doc'?
         // YES. ProcessPacket uses 'doc'. 'args' points to inside 'doc'.
         // So we MUST NOT clear 'doc' until we are done reading 'args'.
         
         // Solution: Create a temporary FilamentInfo struct on stack
         
         if(!args["lane"].is<int>()) { SendError(id, "BAD_ARGS", "Missing lane"); return; }
         int lane = args["lane"];
         
         // ... (Logic to read args into stack vars)
         FilamentInfo info;
         FilamentState &current = UnitState::GetFilament(lane);
         memcpy(info.ID, current.ID, sizeof(info.ID));
         memcpy(info.name, current.name, sizeof(info.name));
         info.color_R = current.color_R;
         info.color_G = current.color_G;
         info.color_B = current.color_B;
         info.color_A = current.color_A;
         info.temperature_min = current.temperature_min;
         info.temperature_max = current.temperature_max;
         if(args["id_str"].is<const char*>()) info.SetID(args["id_str"]);
         if(args["name"].is<const char*>()) info.SetName(args["name"]);
         if(args["temp_min"].is<int>()) info.temperature_min = args["temp_min"];
         if(args["temp_max"].is<int>()) info.temperature_max = args["temp_max"];
         
         if(args["color"].is<JsonArray>()) {
             JsonArray c = args["color"];
             if(c.size() >= 3) {
                 info.color_R = c[0]; info.color_G = c[1]; info.color_B = c[2];
                 if(c.size() > 3) info.color_A = c[3]; else info.color_A = 255;
             }
         }
         
         float meters = -1.0f;
         if(args["meters"].is<float>()) meters = args["meters"];
         
         // Now we are done with args.
         ControlLogic::SetFilamentInfoAction(lane, info, meters);
         SendOk(id);
    }
References FilamentInfo::color_A, FilamentInfo::color_B, FilamentInfo::color_G, FilamentInfo::color_R, UnitState::GetFilament(), FilamentInfo::ID, FilamentInfo::name, SendError(), SendOk(), ControlLogic::SetFilamentInfoAction(), FilamentInfo::SetID(), FilamentInfo::SetName(), FilamentInfo::temperature_max, and FilamentInfo::temperature_min.
Referenced by ProcessPacket().
HandleStatus()
void KlipperCLI::HandleStatus (int id, JsonObject args)
Handler for STATUS command.
Returns a comprehensive state of all 4 lanes, including motion state, filament sensors, odometer meters, pressure, and filament metadata. Uses manual string construction to avoid heap memory issues with large JSON.
Definition at line 111 of file KlipperCLI.cpp.
                                               {
         // Manual JSON construction to avoid Heap Fragmentation/Overflow
         // 2048 bytes static buffer for full status
         static char output[2048];
         int offset = 0;
         
         // Header
         offset += snprintf(output + offset, sizeof(output) - offset,
             "{\"id\":%d,\"cmd\":\"STATUS\",\"ok\":true,\"lanes\":[", id);
             
         uint16_t sensors = ControlLogic::GetSensorState();
         
         for(int i=0; i<4; i++) {
            // Separator
            if(i > 0) offset += snprintf(output + offset, sizeof(output) - offset, ",");
            
            int m_val = ControlLogic::GetLaneMotion(i);
            const char* m_str = "Idle";
            switch(m_val) {
                case 0: m_str = "Idle"; break;
                case 1: m_str = "Feed"; break;
                case 2: m_str = "Retract"; break;
                case 3: m_str = "SlowFeed"; break;
                case 5: m_str = "AutoFeed"; break;
                case 7: m_str = "VelCtrl"; break;
                default: m_str = "Idle"; break;
            }
            
            
            FilamentState &f = UnitState::GetFilament(i);
            
            // Safe Strings (Null-terminated)
            char safe_id[9]; memcpy(safe_id, f.ID, 8); safe_id[8]=0;
            char safe_name[21]; memcpy(safe_name, f.name, 20); safe_name[20]=0;
            
            // Manual Float formatting (printf %f not supported)
            int m_int = (int)f.meters;
            int m_dec = (int)((f.meters - m_int) * 100);
            if(m_dec < 0) m_dec = -m_dec; // Handle negative decimal part if any
            
            int p_int = f.pressure / 1000;
            int p_dec = f.pressure % 1000;
            
            offset += snprintf(output + offset, sizeof(output) - offset,
                "{\"id\":%d,\"present\":%s,\"motion\":\"%s\",\"meters\":%d.%02d,\"pressure\":%d.%03d,\"rfid\":\"%s\",\"name\":\"%s\",\"temp_min\":%d,\"temp_max\":%d,\"color\":[%d,%d,%d,%d]}",
                i,
                (sensors & (1<<i)) ? "true" : "false",
                m_str,
                m_int, m_dec,
                p_int, p_dec,
                safe_id,
                safe_name,
                f.temperature_min,
                f.temperature_max,
                f.color_R, f.color_G, f.color_B, f.color_A
            );
            
            // Safety break
            if (offset >= (int)sizeof(output) - 100) break;
         }
         
         // Footer
         offset += snprintf(output + offset, sizeof(output) - offset, "]}\r\n");
         
         // Send
         Hardware::UART_Send((const uint8_t*)output, offset);
    }
References FilamentInfo::color_A, FilamentInfo::color_B, FilamentInfo::color_G, FilamentInfo::color_R, UnitState::GetFilament(), ControlLogic::GetLaneMotion(), ControlLogic::GetSensorState(), FilamentInfo::ID, FilamentState::meters, FilamentInfo::name, FilamentState::pressure, FilamentInfo::temperature_max, FilamentInfo::temperature_min, and Hardware::UART_Send().
Referenced by ProcessPacket().
HandleStop()
void KlipperCLI::HandleStop (int id, JsonObject args)
Handler for STOP command.
Cancels all motion immediately.
Definition at line 255 of file KlipperCLI.cpp.
                                             {
        ControlLogic::StopAll();
        SendOk(id, "STOPPED", "All motion stopped");
    }
References SendOk(), and ControlLogic::StopAll().
Referenced by ProcessPacket().
Init()
void KlipperCLI::Init ()
Initialize Klipper CLI.
Sends a startup message.
Definition at line 439 of file KlipperCLI.cpp.
                {
        Hardware::UART_Send((const uint8_t*)"{\"event\":\"STARTUP\",\"msg\":\"KlipperCLI Ready\"}\r\n", 52);
    }
References Hardware::UART_Send().
Referenced by CommandRouter::Init().
IsConnected()
bool KlipperCLI::IsConnected ()
ProcessPacket()
void KlipperCLI::ProcessPacket (char * json_str)
Parse and Dispatch a JSON Packet.
Deserializes the buffer and routes to the appropriate handler based on "cmd".
Definition at line 400 of file KlipperCLI.cpp.
                                       {
        doc.clear();
        DeserializationError error = deserializeJson(doc, json_str);
        if (error) {
            // Malformed JSON, maybe echo back error if possible, or ignore
            const char* err_msg = "{\"ok\":false,\"msg\":\"JSON Parse Error\"}\n";
            Hardware::UART_Send((const uint8_t*)err_msg, strlen(err_msg));
            return;
        }
        int id = doc["id"] | 0;
        const char* cmd = doc["cmd"];
        JsonObject args = doc["args"];
        if (!cmd) return;
        if (strcmp(cmd, "PING") == 0) HandlePing(id, args);
        else if (strcmp(cmd, "STATUS") == 0) HandleStatus(id, args);
        else if (strcmp(cmd, "GET_SENSORS") == 0) HandleGetSensors(id, args);
        else if (strcmp(cmd, "MOVE") == 0) HandleMove(id, args);
        else if (strcmp(cmd, "STOP") == 0) HandleStop(id, args);
        else if (strcmp(cmd, "SELECT_LANE") == 0) HandleSelectLane(id, args);
        else if (strcmp(cmd, "SET_AUTO_FEED") == 0) HandleSetAutoFeed(id, args);
        else if (strcmp(cmd, "GET_FILAMENT_INFO") == 0) HandleGetFilamentInfo(id, args);
        else if (strcmp(cmd, "SET_FILAMENT_INFO") == 0) HandleSetFilamentInfo(id, args);
        else {
            SendError(id, "UNKNOWN_CMD", cmd);
        }
    }
References doc, HandleGetFilamentInfo(), HandleGetSensors(), HandleMove(), HandlePing(), HandleSelectLane(), HandleSetAutoFeed(), HandleSetFilamentInfo(), HandleStatus(), HandleStop(), SendError(), and Hardware::UART_Send().
Referenced by Run().
Run()
void KlipperCLI::Run ()
Main Execution Loop.
Checks if a full line is received, processes it, and resets the buffer.
Definition at line 449 of file KlipperCLI.cpp.
               {
        if (packet_ready) {
             ProcessPacket(rx_buffer);
             // Reset buffer
             rx_idx = 0;
             packet_ready = false;
        }
    }
References packet_ready, ProcessPacket(), rx_buffer, and rx_idx.
Referenced by CommandRouter::Run().
SendError()
void KlipperCLI::SendError (int id, const char * code, const char * msg)
Helper to send an Error response.
Parameters
id Request ID.
code Error Code String.
msg Descriptive Message.
Definition at line 56 of file KlipperCLI.cpp.
                                                              {
        doc.clear();
        doc["id"] = id;
        doc["ok"] = false;
        doc["code"] = code;
        doc["msg"] = msg;
        SendResponse(doc);
    }
References doc, and SendResponse().
Referenced by HandleGetFilamentInfo(), HandleMove(), HandleSelectLane(), HandleSetAutoFeed(), HandleSetFilamentInfo(), and ProcessPacket().
SendOk()
void KlipperCLI::SendOk (int id, const char * code = nullptr, const char * msg = nullptr)
Helper to send a Success (OK) response.
Parameters
id Request ID.
code Optional code.
msg Optional message.
Definition at line 73 of file KlipperCLI.cpp.
                                                                               {
        doc.clear();
        doc["id"] = id;
        doc["ok"] = true;
        if(code) doc["code"] = code;
        if(msg) doc["msg"] = msg;
        SendResponse(doc);
    }
References doc, and SendResponse().
Referenced by HandleMove(), HandleSelectLane(), HandleSetAutoFeed(), HandleSetFilamentInfo(), and HandleStop().
SendResponse()
void KlipperCLI::SendResponse (JsonDocument & d)
Serialize and send a JSON response.
Serializes the document to a buffer, appends CR/LF, and sends via UART.
Parameters
d The JSON Document to serialize.
Definition at line 35 of file KlipperCLI.cpp.
                                       {
        // Serialize to buffer
        static char output[1200]; // Increased buffer slightly
        size_t len = serializeJson(d, output, sizeof(output) - 2);
        
        // Append Newline
        output[len++] = '\r';
        output[len++] = '\n';
        
        // Send via Hardware UART
        Hardware::UART_Send((const uint8_t*)output, len);
    }
References Hardware::UART_Send().
Referenced by HandleGetSensors(), HandlePing(), SendError(), and SendOk().
Variable Documentation
doc
JsonDocument KlipperCLI::doc [static]
Definition at line 24 of file KlipperCLI.cpp.
Referenced by HandleGetSensors(), HandlePing(), ProcessPacket(), SendError(), and SendOk().
packet_ready
volatile bool KlipperCLI::packet_ready = false [static]
Definition at line 431 of file KlipperCLI.cpp.
Referenced by FeedByte(), and Run().
rx_buffer
char KlipperCLI::rx_buffer[1024] [static]
Definition at line 19 of file KlipperCLI.cpp.
Referenced by FeedByte(), and Run().
rx_idx
int KlipperCLI::rx_idx = 0 [static]
Definition at line 20 of file KlipperCLI.cpp.
Referenced by FeedByte(), and Run().