Hardware Namespace Reference
Functions
void InitBase ()
Initialize minimal Hardware Base.
void Watchdog_Disable ()
Disable the Window Watchdog.
void System_Init ()
Configure System Clocks and Pin Remapping.
void DelayUS (uint32_t time)
Microsecond Delay.
void DelayMS (uint32_t time)
Millisecond Delay.
uint64_t GetTime ()
Get System Time in Milliseconds.
void UART_SetRxCallback (void(*callback)(uint8_t))
Register a callback for UART1 RX.
void InitUART (bool isKlipper)
Initialize UART1 for Bus/Serial communication.
void USART1_IRQHandler (void)
UART1 Interrupt Service Routine.
void UART_SendByte (uint8_t data)
Send a single byte blocking.
void UART_Send (const uint8_t *data, uint16_t length)
Send a buffer via UART1.
void ADC_Init ()
Initialize the Analog-to-Digital Converter.
float * ADC_GetValues ()
Get filtered ADC voltage values.
void PWM_Init ()
Initialize PWM Timers for Motor Control.
void PWM_Set (uint8_t channel, int PWM)
Set PWM duty cycle for a Motor Channel.
void LED_Init ()
Initialize NeoPixel LEDs.
void LED_SetColor (uint8_t channel, int led_idx, uint8_t r, uint8_t g, uint8_t b)
Set Color of a specific LED.
void LED_Show ()
Update LED Hardware.
void LED_SetBrightness (uint8_t brightness)
Set Global Brightness for LEDs.
Variables
static void(* uart_rx_callback)(uint8_t) = nullptr
Function Documentation
ADC_GetValues()
float * Hardware::ADC_GetValues ()
Get filtered ADC voltage values.
Calculates the average of the DMA buffer for each channel, converts to Voltage, and returns the array.
Returns
float* Pointer to array of 8 float voltages (0.0 - 3.3V).
Definition at line 387 of file Hardware.cpp.
                           {
        for (int i = 0; i < 8; i++) {
            int data_sum = 0;
            for (int j = 0; j < ADC_filter_n; j++) {
                uint16_t val = ADC_data[j][i];
                int sum = val + ADC_Calibrattion_Val;
                if (sum < 0 || val == 0) ;
                else if (sum > 4095 || val == 4095) data_sum += 4095;
                else data_sum += sum;
            }
            data_sum >>= ADC_filter_n_pow;
            ADC_V[i] = ((float)data_sum) / 4096 * 3.3;
        }
        return ADC_V;
    }
References ADC_Calibrattion_Val, ADC_data, ADC_filter_n, ADC_filter_n_pow, and ADC_V.
Referenced by ControlLogic::MC_PULL_ONLINE_read().
ADC_Init()
void Hardware::ADC_Init ()
Initialize the Analog-to-Digital Converter.
Configures GPIO (PA0-PA7), DMA1 Channel 1 (Circular Buffer), and ADC1. Runs calibration and starts continuous conversion via DMA.
Definition at line 317 of file Hardware.cpp.
                    {
        // GPIO
        {
            RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA, ENABLE);
            GPIO_InitTypeDef GPIO_InitStructure;
            GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AIN;
            GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
            GPIO_InitStructure.GPIO_Pin = GPIO_Pin_0 | GPIO_Pin_1 | GPIO_Pin_2 | GPIO_Pin_3 | GPIO_Pin_4 | GPIO_Pin_5 | GPIO_Pin_6 | GPIO_Pin_7;
            GPIO_Init(GPIOA, &GPIO_InitStructure);
        }
        // DMA
        {
            DMA_InitTypeDef DMA_InitStructure;
            RCC_AHBPeriphClockCmd(RCC_AHBPeriph_DMA1, ENABLE);
            DMA_DeInit(DMA1_Channel1);
            DMA_InitStructure.DMA_PeripheralBaseAddr = (uint32_t)&ADC1->RDATAR;
            DMA_InitStructure.DMA_MemoryBaseAddr = (uint32_t)ADC_data;
            DMA_InitStructure.DMA_DIR = DMA_DIR_PeripheralSRC;
            DMA_InitStructure.DMA_BufferSize = ADC_filter_n * 8;
            DMA_InitStructure.DMA_PeripheralInc = DMA_PeripheralInc_Disable;
            DMA_InitStructure.DMA_MemoryInc = DMA_MemoryInc_Enable;
            DMA_InitStructure.DMA_PeripheralDataSize = DMA_PeripheralDataSize_HalfWord;
            DMA_InitStructure.DMA_MemoryDataSize = DMA_MemoryDataSize_HalfWord;
            DMA_InitStructure.DMA_Mode = DMA_Mode_Circular;
            DMA_InitStructure.DMA_Priority = DMA_Priority_VeryHigh;
            DMA_InitStructure.DMA_M2M = DMA_M2M_Disable;
            DMA_Init(DMA1_Channel1, &DMA_InitStructure);
            DMA_Cmd(DMA1_Channel1, ENABLE);
        }
        // ADC
        {
            ADC_DeInit(ADC1);
            RCC_ADCCLKConfig(RCC_PCLK2_Div8);
            RCC_APB2PeriphClockCmd(RCC_APB2Periph_ADC1, ENABLE);
            ADC_InitTypeDef ADC_InitStructure;
            ADC_InitStructure.ADC_Mode = ADC_Mode_Independent;
            ADC_InitStructure.ADC_ScanConvMode = ENABLE;
            ADC_InitStructure.ADC_ContinuousConvMode = ENABLE;
            ADC_InitStructure.ADC_ExternalTrigConv = ADC_ExternalTrigConv_None;
            ADC_InitStructure.ADC_DataAlign = ADC_DataAlign_Right;
            ADC_InitStructure.ADC_NbrOfChannel = 8;
            ADC_Init(ADC1, &ADC_InitStructure);
            ADC_Cmd(ADC1, ENABLE);
            ADC_BufferCmd(ADC1, DISABLE);
            ADC_ResetCalibration(ADC1);
            while (ADC_GetResetCalibrationStatus(ADC1));
            ADC_StartCalibration(ADC1);
            while (ADC_GetCalibrationStatus(ADC1));
            ADC_Calibrattion_Val = Get_CalibrationValue(ADC1);
            for (int i = 0; i < 8; i++)
                ADC_RegularChannelConfig(ADC1, i, i + 1, ADC_SampleTime_239Cycles5);
            ADC_DMACmd(ADC1, ENABLE);
            ADC_SoftwareStartConvCmd(ADC1, ENABLE);
        }
        DelayMS(256); // Wait for buffer fill (ADC_filter_n = 256)
    }
References ADC_Calibrattion_Val, ADC_data, ADC_filter_n, ADC_Init(), and DelayMS().
Referenced by ADC_Init(), ControlLogic::Init(), and InitBase().
DelayMS()
void Hardware::DelayMS (uint32_t time)
Millisecond Delay.
Parameters
time Milliseconds to wait.
Definition at line 105 of file Hardware.cpp.
                                {
        delay(time);
    }
Referenced by ADC_Init(), InitBase(), and CommandRouter::Run().
DelayUS()
void Hardware::DelayUS (uint32_t time)
Microsecond Delay.
Parameters
time Microseconds to wait.
Definition at line 95 of file Hardware.cpp.
                                {
        delayMicroseconds(time);
    }
Referenced by UART_Send(), and UART_SendByte().
GetTime()
uint64_t Hardware::GetTime ()
Get System Time in Milliseconds.
Returns
uint64_t Time since boot (approx) in ms.
Definition at line 115 of file Hardware.cpp.
                       {
        return get_time64();
    }
References get_time64().
Referenced by ControlLogic::get_time64(), KlipperCLI::HandlePing(), ControlLogic::motor_motion_switch(), CommandRouter::Run(), ControlLogic::Run(), ControlLogic::SetNeedToSave(), and ControlLogic::UpdateConnectivity().
InitBase()
void Hardware::InitBase ()
Initialize minimal Hardware Base.
Disables Watchdog, Configures Clock/AFIO, Inits LEDs, ADC, PWM. Performs a boot LED sequence.
Definition at line 52 of file Hardware.cpp.
                    {
        Watchdog_Disable(); // Disable WWDG first!
        System_Init();
        LED_Init(); // Init LEDs
        // UART_Init moved to explicit call
        ADC_Init();
        PWM_Init();
        
        // Debug Flash: Red -> Blue -> Green
        LED_SetColor(4, 0, 50, 0, 0); LED_Show(); DelayMS(200);
        LED_SetColor(4, 0, 0, 0, 50); LED_Show(); DelayMS(200);
        LED_SetColor(4, 0, 0, 50, 0); LED_Show(); DelayMS(200);
        LED_SetColor(4, 0, 0, 0, 0); LED_Show();
    }
References ADC_Init(), DelayMS(), LED_Init(), LED_SetColor(), LED_Show(), PWM_Init(), System_Init(), and Watchdog_Disable().
Referenced by setup().
InitUART()
void Hardware::InitUART (bool isKlipper)
Initialize UART1 for Bus/Serial communication.
Configures PA9(TX), PA10(RX), PA12(DE).
Parameters
isKlipper True for 250k baud standard serial. False for 1.25M baud 9-bit bus.
Definition at line 140 of file Hardware.cpp.
                                  {
        GPIO_InitTypeDef GPIO_InitStructure = {0};
        USART_InitTypeDef USART_InitStructure = {0};
        NVIC_InitTypeDef NVIC_InitStructure = {0};
        RCC_APB2PeriphClockCmd(RCC_APB2Periph_USART1, ENABLE);
        RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA, ENABLE);
        RCC_AHBPeriphClockCmd(RCC_AHBPeriph_DMA1, ENABLE);
        /* USART1 TX-->A.9 RX-->A.10 */
        GPIO_InitStructure.GPIO_Pin = GPIO_Pin_9; // TX
        GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
        GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF_PP;
        GPIO_Init(GPIOA, &GPIO_InitStructure);
        GPIO_InitStructure.GPIO_Pin = GPIO_Pin_10; // RX
        GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IPU;
        GPIO_Init(GPIOA, &GPIO_InitStructure);
        GPIO_InitStructure.GPIO_Pin = GPIO_Pin_12; // DE
        GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
        GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;
        GPIO_Init(GPIOA, &GPIO_InitStructure);
        GPIOA->BCR = GPIO_Pin_12;
        if (isKlipper) {
            // Standard/Klipper Mode
            USART_InitStructure.USART_BaudRate = 250000;
            USART_InitStructure.USART_Parity = USART_Parity_No;
            USART_InitStructure.USART_WordLength = USART_WordLength_8b;
        } else {
            // BambuBus Mode
            USART_InitStructure.USART_BaudRate = 1250000;
            USART_InitStructure.USART_Parity = USART_Parity_Even;
            USART_InitStructure.USART_WordLength = USART_WordLength_9b;
        }
        USART_InitStructure.USART_StopBits = USART_StopBits_1;
        USART_InitStructure.USART_HardwareFlowControl = USART_HardwareFlowControl_None;
        USART_InitStructure.USART_Mode = USART_Mode_Tx | USART_Mode_Rx;
        USART_Init(USART1, &USART_InitStructure);
        USART_ITConfig(USART1, USART_IT_RXNE, ENABLE);
        USART_ITConfig(USART1, USART_IT_TC, ENABLE);
        NVIC_InitStructure.NVIC_IRQChannel = USART1_IRQn;
        NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 0;
        NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0;
        NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
        NVIC_Init(&NVIC_InitStructure);
        // Configure DMA1 channel 4 for USART1 TX
        Bambubus_DMA_InitStructure.DMA_PeripheralBaseAddr = (uint32_t)&USART1->DATAR;
        Bambubus_DMA_InitStructure.DMA_MemoryBaseAddr = (uint32_t)0;
        Bambubus_DMA_InitStructure.DMA_DIR = DMA_DIR_PeripheralDST;
        Bambubus_DMA_InitStructure.DMA_Mode = DMA_Mode_Normal;
        Bambubus_DMA_InitStructure.DMA_PeripheralInc = DMA_PeripheralInc_Disable;
        Bambubus_DMA_InitStructure.DMA_MemoryInc = DMA_MemoryInc_Enable;
        Bambubus_DMA_InitStructure.DMA_Priority = DMA_Priority_VeryHigh;
        Bambubus_DMA_InitStructure.DMA_M2M = DMA_M2M_Disable;
        Bambubus_DMA_InitStructure.DMA_MemoryDataSize = DMA_MemoryDataSize_Byte;
        Bambubus_DMA_InitStructure.DMA_PeripheralDataSize = DMA_PeripheralDataSize_Byte;
        Bambubus_DMA_InitStructure.DMA_BufferSize = 0;
        USART_Cmd(USART1, ENABLE);
    }
References Bambubus_DMA_InitStructure.
Referenced by setup().
LED_Init()
void Hardware::LED_Init ()
Initialize NeoPixel LEDs.
Starts the Adafruit_NeoPixel instances for mainboard and channels.
Definition at line 515 of file Hardware.cpp.
                    {
        strip_PD1.begin();
        for(int i=0; i<4; i++) strip_channel[i].begin();
    }
References strip_channel, and strip_PD1().
Referenced by InitBase().
LED_SetBrightness()
void Hardware::LED_SetBrightness (uint8_t brightness)
Set Global Brightness for LEDs.
Parameters
brightness Brightness (0-255, 0 uses defaults).
Definition at line 555 of file Hardware.cpp.
                                               {
         // This is global brightness scaling, usually we set it once.
         // Original code had different brightness for PD1 (35) and channels (15).
         
         // If this function is intended to set a global brightness level, it might need more logic
         // or separate functions. For now let's reproduce original setup if brightness == 0 (init).
         
         // Allow custom brightness
         strip_PD1.setBrightness(brightness > 0 ? brightness : 35);
         for(int i=0; i<4; i++) strip_channel[i].setBrightness(brightness > 0 ? brightness : 15);
    }
References strip_channel, and strip_PD1().
Referenced by setup().
LED_SetColor()
void Hardware::LED_SetColor (uint8_t channel, int led_idx, uint8_t r, uint8_t g, uint8_t b)
Set Color of a specific LED.
Parameters
channel Channel (0-3) or Mainboard (4).
led_idx Index of LED in the strip (0-1 typically).
r Red (0-255).
g Green (0-255).
b Blue (0-255).
Definition at line 530 of file Hardware.cpp.
                                                                                     {
        if (channel < 4) {
             strip_channel[channel].setPixelColor(led_idx, strip_channel[channel].Color(r, g, b));
        } else if (channel == 4) { // Mainboard
             strip_PD1.setPixelColor(led_idx, strip_PD1.Color(r, g, b));
        }
    }
References strip_channel, and strip_PD1().
Referenced by InitBase(), ControlLogic::motor_motion_switch(), ControlLogic::Prepare_For_filament_Pull_Back(), ControlLogic::Run(), and ControlLogic::MotorChannel::UpdateLEDStatus().
LED_Show()
void Hardware::LED_Show ()
Update LED Hardware.
Pushes the memory buffer to the LED strips.
Definition at line 544 of file Hardware.cpp.
                    {
        strip_PD1.show();
        for(int i=0; i<4; i++) strip_channel[i].show();
    }
References strip_channel, and strip_PD1().
Referenced by InitBase(), ControlLogic::Run(), and setup().
PWM_Init()
void Hardware::PWM_Init ()
Initialize PWM Timers for Motor Control.
Configures TIM2, TIM3, TIM4 channels for motor driver control pins. Remaps pins as necessary.
Definition at line 411 of file Hardware.cpp.
                    {
        GPIO_InitTypeDef GPIO_InitStructure;
        RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA | RCC_APB2Periph_GPIOB, ENABLE);
        GPIO_InitStructure.GPIO_Pin = GPIO_Pin_3 | GPIO_Pin_4 | GPIO_Pin_5 |
                                      GPIO_Pin_6 | GPIO_Pin_7 | GPIO_Pin_8 | GPIO_Pin_9;
        GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF_PP;
        GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
        GPIO_Init(GPIOB, &GPIO_InitStructure);
        GPIO_InitStructure.GPIO_Pin = GPIO_Pin_15;
        GPIO_Init(GPIOA, &GPIO_InitStructure);
        RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO, ENABLE);
        RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM2, ENABLE);
        RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM3, ENABLE);
        RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM4, ENABLE);
        // Remap Pins for Motor Control
        GPIO_PinRemapConfig(GPIO_FullRemap_TIM2, ENABLE); // TIM2 CH1/CH2 -> PA15/PB3
        GPIO_PinRemapConfig(GPIO_PartialRemap_TIM3, ENABLE); // TIM3 CH1/CH2 -> PB4/PB5
        TIM_TimeBaseInitTypeDef TIM_TimeBaseStructure;
        TIM_OCInitTypeDef TIM_OCInitStructure;
        TIM_TimeBaseStructure.TIM_Period = 999;
        TIM_TimeBaseStructure.TIM_Prescaler = 1;
        TIM_TimeBaseStructure.TIM_ClockDivision = 0;
        TIM_TimeBaseStructure.TIM_CounterMode = TIM_CounterMode_Up;
        TIM_TimeBaseInit(TIM2, &TIM_TimeBaseStructure);
        TIM_TimeBaseInit(TIM3, &TIM_TimeBaseStructure);
        TIM_TimeBaseInit(TIM4, &TIM_TimeBaseStructure);
        TIM_OCInitStructure.TIM_OCMode = TIM_OCMode_PWM1;
        TIM_OCInitStructure.TIM_OutputState = TIM_OutputState_Enable;
        TIM_OCInitStructure.TIM_Pulse = 0;
        TIM_OCInitStructure.TIM_OCPolarity = TIM_OCPolarity_High;
        TIM_OC1Init(TIM2, &TIM_OCInitStructure);
        TIM_OC2Init(TIM2, &TIM_OCInitStructure);
        TIM_OC1Init(TIM3, &TIM_OCInitStructure);
        TIM_OC2Init(TIM3, &TIM_OCInitStructure);
        TIM_OC3Init(TIM4, &TIM_OCInitStructure); // Note: Original looked like OC1/2 for TIM4 too? Let's check Motion_control.cpp.
        // Motion_control.cpp: case 1: TIM_SetCompare1(TIM4, set1); ... case 0: TIM_SetCompare3(TIM4, set1); TIM_SetCompare4(TIM4, set2);
        // So TIM4 uses Ch1, Ch2, Ch3, Ch4.
        
        // Re-checking Motion_control.cpp lines 440+:
        // Case 3: TIM2 Ch1/Ch2 (PA15 / PB3? Remap dependent?)
        // Case 2: TIM3 Ch1/Ch2 (PB4 / PB5?)
        // Case 1: TIM4 Ch1/Ch2 (PB6 / PB7)
        // Case 0: TIM4 Ch3/Ch4 (PB8 / PB9)
        
        // So we need to init all those channels.
        TIM_OC1Init(TIM4, &TIM_OCInitStructure);
        TIM_OC2Init(TIM4, &TIM_OCInitStructure);
        TIM_OC3Init(TIM4, &TIM_OCInitStructure);
        TIM_OC4Init(TIM4, &TIM_OCInitStructure);
        TIM_Cmd(TIM2, ENABLE);
        TIM_Cmd(TIM3, ENABLE);
        TIM_Cmd(TIM4, ENABLE);
    }
Referenced by ControlLogic::Init(), and InitBase().
PWM_Set()
void Hardware::PWM_Set (uint8_t channel, int PWM)
Set PWM duty cycle for a Motor Channel.
Parameters
channel Motor Channel (0-3).
PWM Value (-1000 to 1000). Positive for one direction, negative for other.
Definition at line 478 of file Hardware.cpp.
                                           {
        uint16_t set1 = 0, set2 = 0;
        if (PWM > 0) {
            set1 = PWM;
        } else if (PWM < 0) {
            set2 = -PWM;
        } else {
            set1 = 1000;
            set2 = 1000;
        }
        switch (channel) {
        case 3:
            TIM_SetCompare1(TIM2, set1);
            TIM_SetCompare2(TIM2, set2);
            break;
        case 2:
            TIM_SetCompare1(TIM3, set1);
            TIM_SetCompare2(TIM3, set2);
            break;
        case 1:
            TIM_SetCompare1(TIM4, set1);
            TIM_SetCompare2(TIM4, set2);
            break;
        case 0:
            TIM_SetCompare3(TIM4, set1);
            TIM_SetCompare4(TIM4, set2);
            break;
        }
    }
Referenced by ControlLogic::MotorChannel::Run().
System_Init()
void Hardware::System_Init ()
Configure System Clocks and Pin Remapping.
Enables AFIO and sets PD0/PD1 remapping for HSE/LSE reuse if needed.
Definition at line 84 of file Hardware.cpp.
                       {
        RCC_APB2PeriphClockCmd(RCC_APB2Periph_AFIO, ENABLE);
        GPIO_PinRemapConfig(GPIO_Remap_PD01, ENABLE);
    }
Referenced by InitBase().
UART_Send()
void Hardware::UART_Send (const uint8_t * data, uint16_t length)
Send a buffer via UART1.
Note
If STANDARD_SERIAL is defined, uses blocking send. If not (BambuBus mode), uses DMA for high speed transfer.
Parameters
data Pointer to data.
length Length of data.
Definition at line 261 of file Hardware.cpp.
                                                         {
#if defined(STANDARD_SERIAL)
        // Blocking mode for CLI interactivity (safe with ISR echo)
        
        // Disable TC interrupt to prevent ISR from disabling DE prematurely
        USART_ITConfig(USART1, USART_IT_TC, DISABLE);
        
        GPIOA->BSHR = GPIO_Pin_12; // Set High (TX) for RS485
        for (uint16_t i = 0; i < length; i++) {
             UART_SendByte(data[i]);
        }
        
        // Re-enable TC interrupt so ISR can disable DE when the *last byte* is actually done
        USART_ITConfig(USART1, USART_IT_TC, ENABLE);
        
        // ISR handles DE pin Disable on TC interrupt.
        
#else
        // DMA mode for High Speed Bus (BambuBus)
        
        // Check if DMA is currently enabled (transfer active)
        if (DMA1_Channel4->CFGR & 0x01) {
             // Wait for data transfer to complete
             uint32_t timeout = 100000;
             while (DMA_GetCurrDataCounter(DMA1_Channel4) != 0 && timeout--) {
                 DelayUS(1);
             }
             // Ensure Transmission Complete flag is set (buffer clear)
             timeout = 100000;
             while (USART_GetFlagStatus(USART1, USART_FLAG_TC) == RESET && timeout--) {
                 DelayUS(1);
             }
             // Create a small gap or ensure Disable is clean
             DMA_Cmd(DMA1_Channel4, DISABLE);
        }
        DMA_DeInit(DMA1_Channel4);
        Bambubus_DMA_InitStructure.DMA_MemoryBaseAddr = (uint32_t)data;
        Bambubus_DMA_InitStructure.DMA_BufferSize = length;
        DMA_Init(DMA1_Channel4, &Bambubus_DMA_InitStructure);
        DMA_Cmd(DMA1_Channel4, ENABLE);
        GPIOA->BSHR = GPIO_Pin_12;
        USART_DMACmd(USART1, USART_DMAReq_Tx, ENABLE);
#endif
    }
References Bambubus_DMA_InitStructure, DelayUS(), and UART_SendByte().
Referenced by KlipperCLI::HandleGetFilamentInfo(), KlipperCLI::HandleStatus(), KlipperCLI::Init(), ControlLogic::motor_motion_switch(), KlipperCLI::ProcessPacket(), CommandRouter::SendPacket(), and KlipperCLI::SendResponse().
UART_SendByte()
void Hardware::UART_SendByte (uint8_t data)
Send a single byte blocking.
Parameters
data Byte to send.
Definition at line 243 of file Hardware.cpp.
                                     {
         uint32_t timeout = 10000;
         while (USART_GetFlagStatus(USART1, USART_FLAG_TXE) == RESET && timeout--) {
             DelayUS(1);
         }
         if (timeout > 0) USART_SendData(USART1, data);
    }
References DelayUS().
Referenced by UART_Send().
UART_SetRxCallback()
void Hardware::UART_SetRxCallback (void(* callback)(uint8_t))
Register a callback for UART1 RX.
Parameters
callback Function pointer void(uint8_t byte).
Definition at line 128 of file Hardware.cpp.
                                                       {
        uart_rx_callback = callback;
    }
References uart_rx_callback.
Referenced by CommandRouter::Init().
USART1_IRQHandler()
void Hardware::USART1_IRQHandler (void)
UART1 Interrupt Service Routine.
Handles RXNE (Receive Data) and TC (Transmission Complete) logic. Manages RS485 DE pin (PA12).
Definition at line 212 of file Hardware.cpp.
    {
        volatile uint32_t sr = USART1->STATR; // Read Status Register
        volatile uint32_t dr;
        
        // Check for Read Data Register Not Empty (RXNE) OR Overrun Error (ORE)
        // Note: Reading SR then DR clears ORE, NE, FE, PE
        if ((sr & USART_FLAG_RXNE) || (sr & USART_FLAG_ORE))
        {
            dr = USART1->DATAR; // Read Data Register to clear flags
            // Only convert to byte and callback if it was a valid RXNE
            // (ORE might set RXNE too, or just ORE)
            if (sr & USART_FLAG_RXNE) {
                if(uart_rx_callback) uart_rx_callback((uint8_t)dr);
            }
        }
        // Check for Transmission Complete (TC)
        if (sr & USART_FLAG_TC)
        {
            USART_ClearITPendingBit(USART1, USART_IT_TC);
            GPIOA->BCR = GPIO_Pin_12; // Disable DE
        }
    }
References uart_rx_callback.
Watchdog_Disable()
void Hardware::Watchdog_Disable ()
Disable the Window Watchdog.
Essential for debugging or development where timing isn't strict yet.
Definition at line 73 of file Hardware.cpp.
                            {
        WWDG_DeInit();
        RCC_APB1PeriphClockCmd(RCC_APB1Periph_WWDG, DISABLE);
    }
Referenced by InitBase().
Variable Documentation
uart_rx_callback
void(* Hardware::uart_rx_callback) (uint8_t) (uint8_t) = nullptr [static]
Definition at line 120 of file Hardware.cpp.
Referenced by UART_SetRxCallback(), and USART1_IRQHandler().