CommandRouter Namespace Reference
Classes
struct RouteEntry
Typedefs
typedef void(* PacketHandler) (uint8_t *buffer, uint16_t length)
Functions
void HandleLongPacket (uint8_t *buffer, uint16_t length)
wrapper to handle Long Packets by parsing and dispatching.
void Init (bool isKlipper)
Initialize the Command Router and CLI subsystems.
void Route (UnifiedCommandType type, uint8_t *buffer, uint16_t length)
Route an incoming command to its specific handler.
void Run ()
Main execution loop for the Router.
void SendPacket (uint8_t *data, uint16_t length)
Send a raw data packet via UART.
Variables
static uint64_t last_packet_time = 0
static uint8_t process_buffer [1024]
static volatile uint16_t process_len = 0
static volatile bool process_ready = false
static const RouteEntry routeTable []
static const int routeTableSize = sizeof(routeTable) / sizeof(RouteEntry)
Typedef Documentation
PacketHandler
typedef void(* CommandRouter::PacketHandler) (uint8_t *buffer, uint16_t length)
Definition at line 24 of file CommandRouter.cpp.
Function Documentation
HandleLongPacket()
void CommandRouter::HandleLongPacket (uint8_t * buffer, uint16_t length)
wrapper to handle Long Packets by parsing and dispatching.
Parses the raw buffer into a long_packge_data struct and passes it to ControlLogic::ProcessLongPacket.
Parameters
buffer Raw packet buffer.
length Length of the packet.
Definition at line 61 of file CommandRouter.cpp.
                                                            {
         long_packge_data data;
         BambuBusProtocol::ParseLongPacket(buffer, length, &data);
         ControlLogic::ProcessLongPacket(data);
    }
References BambuBusProtocol::ParseLongPacket(), and ControlLogic::ProcessLongPacket().
Referenced by Route().
Init()
void CommandRouter::Init (bool isKlipper)
Initialize the Command Router and CLI subsystems.
Sets up the UART Rx callbacks based on the boot mode (Klipper vs Bus). Initializes the appropriate CLI or Protocol handler.
Parameters
isKlipper True if booting into Klipper mode, False for BambuBus mode.
Definition at line 76 of file CommandRouter.cpp.
                              {
        // Always Init BambuBus as it might be switched to?
        // Or if not standard serial
#ifndef STANDARD_SERIAL
        BambuBusProtocol::Init();
#endif
        
        if (isKlipper) {
            #ifdef STANDARD_SERIAL
                Hardware::UART_SetRxCallback([](uint8_t byte) {
                     if (SerialCLI::Accumulate(byte)) {
                         char* line = SerialCLI::GetInitBuffer();
                         int len = SerialCLI::GetLength();
                         if (len < 1000) {
                             memcpy(process_buffer, line, len);
                             process_buffer[len] = 0;
                             process_len = len;
                             process_ready = true;
                             SerialCLI::Reset();
                         }
                     }
                });
                SerialCLI::Init();
            #else
                Hardware::UART_SetRxCallback([](uint8_t byte) {
                    KlipperCLI::FeedByte(byte);
                });
                KlipperCLI::Init();
            #endif
        } else {
            // Bus Mode
            Hardware::UART_SetRxCallback([](uint8_t byte) {
                if (BambuBusProtocol::ParseByte(byte)) {
                    uint8_t* buffer = BambuBusProtocol::GetRxBuffer();
                    uint16_t length = BambuBusProtocol::GetRxLength();
                    if (length < 1000) {
                        memcpy(process_buffer, buffer, length);
                        process_len = length;
                        process_ready = true;
                    }
                }
            });
        }
    }
References KlipperCLI::FeedByte(), BambuBusProtocol::GetRxBuffer(), BambuBusProtocol::GetRxLength(), BambuBusProtocol::Init(), KlipperCLI::Init(), BambuBusProtocol::ParseByte(), process_buffer, process_len, process_ready, and Hardware::UART_SetRxCallback().
Referenced by setup().
Route()
void CommandRouter::Route (UnifiedCommandType type, uint8_t * buffer, uint16_t length)
Route an incoming command to its specific handler.
Updates connectivity status and dispatches the command based on type. Uses a table lookup for common commands and a switch case for special Long Packet handling.
Parameters
type The Unified Command Type.
buffer Pointer to the command data.
length Length of the command data.
Definition at line 133 of file CommandRouter.cpp.
                                                                          {
        // Generic Connectivity Update
        if (type != UnifiedCommandType::None && type != UnifiedCommandType::Error) {
             ControlLogic::UpdateConnectivity(true);
        } else if (type == UnifiedCommandType::Error) {
             ControlLogic::UpdateConnectivity(false);
             return;
        }
        // Table Lookup
        bool found = false;
        for(int i=0; i<routeTableSize; i++) {
            if (routeTable[i].type == type) {
                routeTable[i].handler(buffer, length);
                found = true;
                break;
            }
        }
        
        if (!found) {
            // Handle special Long Packet types that map to same logic?
            // UnifiedCommandType for Long Packets: MCOnline, ReadFilamentInfo, etc.
            // These all need parsing via ParseLongPacket.
            // We can add them to table pointing to HandleLongPacket wrapper.
            switch(type) {
                case UnifiedCommandType::MCOnline:
                case UnifiedCommandType::ReadFilamentInfo:
                case UnifiedCommandType::SetFilamentInfoType2:
                case UnifiedCommandType::Version:
                case UnifiedCommandType::SerialNumber:
                case UnifiedCommandType::FilamentMotionLong: // Also a long packet
                    HandleLongPacket(buffer, length);
                    break;
                default:
                    break;
            }
        }
    }
References Error, FilamentMotionLong, HandleLongPacket(), MCOnline, None, ReadFilamentInfo, routeTable, routeTableSize, SerialNumber, SetFilamentInfoType2, ControlLogic::UpdateConnectivity(), and Version.
Referenced by Run().
Run()
void CommandRouter::Run ()
Main execution loop for the Router.
Checks for new packets from the underlying protocol (SerialCLI, KlipperCLI, or BambuBus). If a packet is ready, it identifies the type (if Bus mode) and calls Route. Also manages the "Offline" timeout logic (3 seconds).
Definition at line 180 of file CommandRouter.cpp.
               {
        if (ControlLogic::GetBootMode() == ControlLogic::BootMode::Klipper) {
            #ifdef STANDARD_SERIAL
                // Polling if needed?
            #else
                KlipperCLI::Run();
            #endif
        }
        if (process_ready) {
            process_ready = false;
            
            if (ControlLogic::GetBootMode() == ControlLogic::BootMode::Klipper) {
                #ifdef STANDARD_SERIAL
                    SerialCLI::Parse((char*)process_buffer);
                #else
                    KlipperCLI::Run(); // KlipperCLI processes its own buffer usually, but verify?
                    // Actually KlipperCLI::Run handles feeding from buffer if using FeedByte?
                    // The callback calls FeedByte.
                    // process_ready logic is for PACKET extraction.
                    // For KlipperCLI, process_ready is not used if we feed directly in callback?
                    // The Init callback calls FeedByte directly.
                    // So process_ready is NOT set for KlipperCLI.
                    // But for SerialCLI it IS set.
                #endif
            } else {
                // Bus Mode
                Hardware::DelayMS(1);
                BambuBus_package_type bb_type = BambuBusProtocol::IdentifyPacket(process_buffer, process_len);
                UnifiedCommandType unified_type = BambuBusProtocol::GetUnifiedType(bb_type);
                
                if (unified_type != UnifiedCommandType::None) {
                     last_packet_time = Hardware::GetTime();
                     Route(unified_type, process_buffer, process_len);
                } else if (bb_type == BambuBus_package_type::ERROR) {
                     Route(UnifiedCommandType::Error, process_buffer, process_len);
                }
            }
        }
        uint64_t now = Hardware::GetTime();
        if (now - last_packet_time > 3000) {
            ControlLogic::UpdateConnectivity(false);
        }
    }
References Hardware::DelayMS(), ERROR, Error, ControlLogic::GetBootMode(), Hardware::GetTime(), BambuBusProtocol::GetUnifiedType(), BambuBusProtocol::IdentifyPacket(), ControlLogic::Klipper, last_packet_time, None, process_buffer, process_len, process_ready, Route(), KlipperCLI::Run(), and ControlLogic::UpdateConnectivity().
Referenced by loop().
SendPacket()
void CommandRouter::SendPacket (uint8_t * data, uint16_t length)
Send a raw data packet via UART.
Parameters
data Pointer to data to send.
length Length of data.
Definition at line 234 of file CommandRouter.cpp.
                                                    {
#ifdef STANDARD_SERIAL
        // In StandardSerial, we might want to print Debug Hex IF configured,
        // OR we might want to convert the binary response to a human readable response?
        // But ControlLogic generated a binary packet response.
        // For SerialCLI, we probably want to intercept this and print text.
        // But since we are refactoring, SerialCLI` should handle responses itself?
        // However, ControlLogic` calls CommandRouter::SendPacket`.
        // So we interpret it here.
        
        // TODO: Decode packet and print text?
        // Reuse DecodeAndPrintPacket logic from previous version or simplify?
        // For now, let's just print a "TxPacket" debug line so we see what logic sent.
        
        const char* prefix = "[TX] ";
        Hardware::UART_Send((const uint8_t*)prefix, 5);
        for(uint16_t i=0; i<length; i++) {
             char tmp[4];
             sprintf(tmp, "%02X ", data[i]);
             Hardware::UART_Send((const uint8_t*)tmp, strlen(tmp));
        }
        Hardware::UART_Send((const uint8_t*)"\r\n", 2);
#else
        Hardware::UART_Send(data, length);
#endif
    }
References Hardware::UART_Send().
Referenced by ControlLogic::ProcessMotionShortLogic(), ControlLogic::ProcessOnlineDetect(), and ControlLogic::ProcessREQx6().
Variable Documentation
last_packet_time
uint64_t CommandRouter::last_packet_time = 0 [static]
Definition at line 18 of file CommandRouter.cpp.
Referenced by Run().
process_buffer
uint8_t CommandRouter::process_buffer[1024] [static]
Definition at line 19 of file CommandRouter.cpp.
Referenced by Init(), and Run().
process_len
volatile uint16_t CommandRouter::process_len = 0 [static]
Definition at line 20 of file CommandRouter.cpp.
Referenced by Init(), and Run().
process_ready
volatile bool CommandRouter::process_ready = false [static]
Definition at line 21 of file CommandRouter.cpp.
Referenced by Init(), and Run().
routeTable
const RouteEntry CommandRouter::routeTable[] [static]
Initial value:
= {
        { UnifiedCommandType::FilamentMotionShort, ControlLogic::ProcessMotionShort, "MotionShort" },
        { UnifiedCommandType::FilamentMotionLong, ControlLogic::ProcessMotionLong, "MotionLong" },
        { UnifiedCommandType::OnlineDetect, ControlLogic::ProcessOnlineDetect,"OnlineDetect"},
        { UnifiedCommandType::REQx6, ControlLogic::ProcessREQx6, "REQx6" },
        { UnifiedCommandType::SetFilamentInfo, ControlLogic::ProcessSetFilamentInfo, "SetFilament" },
        { UnifiedCommandType::Heartbeat, ControlLogic::ProcessHeartbeat, "Heartbeat" },
        
        
        
        
        
     }
Definition at line 33 of file CommandRouter.cpp.
                                           {
        { UnifiedCommandType::FilamentMotionShort, ControlLogic::ProcessMotionShort, "MotionShort" },
        { UnifiedCommandType::FilamentMotionLong, ControlLogic::ProcessMotionLong, "MotionLong" },
        { UnifiedCommandType::OnlineDetect, ControlLogic::ProcessOnlineDetect,"OnlineDetect"},
        { UnifiedCommandType::REQx6, ControlLogic::ProcessREQx6, "REQx6" },
        { UnifiedCommandType::SetFilamentInfo, ControlLogic::ProcessSetFilamentInfo, "SetFilament" },
        { UnifiedCommandType::Heartbeat, ControlLogic::ProcessHeartbeat, "Heartbeat" },
        // Mapped Long Packets (Handler calls helper that parses long packet)
        // CommandRouter::Route logic for these was effectively parsing long packet then calling ControlLogic::ProcessLongPacket
        // We can make a helper in CommandRouter or ControlLogic.
        // Let's use a generic handler or specific wrapper if needed.
        // For now, mapping to a specialized handler or generic one.
     };
Referenced by Route().
routeTableSize
const int CommandRouter::routeTableSize = sizeof(routeTable) / sizeof(RouteEntry) [static]
Definition at line 47 of file CommandRouter.cpp.
Referenced by Route().